// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate_server_api.py.
use super::*;
impl ServerApiClient {
    /// GET /healthai
    pub async fn healthai(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("Healthai", "GET", "/healthai", "application/json", request).await
    }
    /// GET /healthz
    pub async fn healthz(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("Healthz", "GET", "/healthz", "application/json", request).await
    }
    /// GET /openapi.json
    pub async fn openapi_json(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("OpenapiJson", "GET", "/openapi.json", "application/json", request).await
    }
    /// GET /readyz
    pub async fn readyz(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("Readyz", "GET", "/readyz", "application/json", request).await
    }
    /// POST /v1.2/answers
    pub async fn compose_answer(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ComposeAnswer", "POST", "/v1.2/answers", "application/json", request).await
    }
    /// GET /v1.2/collections/{id}/governance
    pub async fn get_collection_governance(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetCollectionGovernance", "GET", "/v1.2/collections/{id}/governance", "application/json", request).await
    }
    /// PUT /v1.2/collections/{id}/governance
    pub async fn replace_collection_governance(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ReplaceCollectionGovernance", "PUT", "/v1.2/collections/{id}/governance", "application/json", request).await
    }
    /// GET /v1.2/collections/{id}/publications/{publication_id}
    pub async fn authorize_publication(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("AuthorizePublication", "GET", "/v1.2/collections/{id}/publications/{publication_id}", "application/json", request).await
    }
    /// GET /v1.2/collections/{id}/vocabulary
    pub async fn get_collection_vocabulary(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetCollectionVocabulary", "GET", "/v1.2/collections/{id}/vocabulary", "application/json", request).await
    }
    /// PATCH /v1.2/collections/{id}/vocabulary
    pub async fn update_collection_vocabulary(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("UpdateCollectionVocabulary", "PATCH", "/v1.2/collections/{id}/vocabulary", "application/json", request).await
    }
    /// PUT /v1.2/collections/{id}/vocabulary
    pub async fn replace_collection_vocabulary(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ReplaceCollectionVocabulary", "PUT", "/v1.2/collections/{id}/vocabulary", "application/json", request).await
    }
    /// POST /v1.2/collections/{id}/vocabulary/refresh
    pub async fn refresh_collection_vocabulary(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("RefreshCollectionVocabulary", "POST", "/v1.2/collections/{id}/vocabulary/refresh", "application/json", request).await
    }
    /// GET /v1.2/collections/{id}/vocabulary/revision
    pub async fn get_vocabulary_revision(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetVocabularyRevision", "GET", "/v1.2/collections/{id}/vocabulary/revision", "application/json", request).await
    }
    /// POST /v1.2/query
    pub async fn query_collections(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("QueryCollections", "POST", "/v1.2/query", "application/json", request).await
    }
    /// POST /v1.2/search
    pub async fn search_collection(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("SearchCollection", "POST", "/v1.2/search", "application/json", request).await
    }
    /// GET /v1.2/vocabulary-settings
    pub async fn get_vocabulary_settings(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetVocabularySettings", "GET", "/v1.2/vocabulary-settings", "application/json", request).await
    }
    /// PUT /v1.2/vocabulary-settings
    pub async fn replace_vocabulary_settings(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ReplaceVocabularySettings", "PUT", "/v1.2/vocabulary-settings", "application/json", request).await
    }
    /// GET /v1/access-tokens
    pub async fn list_tokens(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ListTokens", "GET", "/v1/access-tokens", "application/json", request).await
    }
    /// POST /v1/access-tokens
    pub async fn issue_access_token(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("IssueAccessToken", "POST", "/v1/access-tokens", "application/json", request).await
    }
    /// POST /v1/access-tokens/{jti}/revoke
    pub async fn revoke_token(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("RevokeToken", "POST", "/v1/access-tokens/{jti}/revoke", "application/json", request).await
    }
    /// GET /v1/authoring/drafts
    pub async fn list_drafts(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ListDrafts", "GET", "/v1/authoring/drafts", "application/json", request).await
    }
    /// POST /v1/authoring/drafts
    pub async fn create_draft(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("CreateDraft", "POST", "/v1/authoring/drafts", "application/json", request).await
    }
    /// DELETE /v1/authoring/drafts/{draft_id}
    pub async fn delete_draft(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("DeleteDraft", "DELETE", "/v1/authoring/drafts/{draft_id}", "application/json", request).await
    }
    /// GET /v1/authoring/drafts/{draft_id}
    pub async fn get_draft(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetDraft", "GET", "/v1/authoring/drafts/{draft_id}", "application/json", request).await
    }
    /// PUT /v1/authoring/drafts/{draft_id}/answers
    pub async fn update_answers(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("UpdateAnswers", "PUT", "/v1/authoring/drafts/{draft_id}/answers", "application/json", request).await
    }
    /// POST /v1/authoring/drafts/{draft_id}/apply
    pub async fn apply_draft(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ApplyDraft", "POST", "/v1/authoring/drafts/{draft_id}/apply", "application/json", request).await
    }
    /// POST /v1/authoring/drafts/{draft_id}/assist
    pub async fn assist_draft(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("AssistDraft", "POST", "/v1/authoring/drafts/{draft_id}/assist", "application/json", request).await
    }
    /// POST /v1/authoring/drafts/{draft_id}/export
    pub async fn export_draft(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ExportDraft", "POST", "/v1/authoring/drafts/{draft_id}/export", "application/json", request).await
    }
    /// POST /v1/authoring/drafts/{draft_id}/validate
    pub async fn validate_draft(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ValidateDraft", "POST", "/v1/authoring/drafts/{draft_id}/validate", "application/json", request).await
    }
    /// GET /v1/authoring/patterns
    pub async fn list_patterns(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ListPatterns", "GET", "/v1/authoring/patterns", "application/json", request).await
    }
    /// GET /v1/authoring/patterns/{id}
    pub async fn get_pattern(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetPattern", "GET", "/v1/authoring/patterns/{id}", "application/json", request).await
    }
    /// GET /v1/budgets/{id}/adjustments
    pub async fn budget_adjustments(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("BudgetAdjustments", "GET", "/v1/budgets/{id}/adjustments", "application/json", request).await
    }
    /// POST /v1/budgets/{id}/adjustments
    pub async fn reconcile_budget(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ReconcileBudget", "POST", "/v1/budgets/{id}/adjustments", "application/json", request).await
    }
    /// GET /v1/budgets/{id}/evidence
    pub async fn budget_evidence(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("BudgetEvidence", "GET", "/v1/budgets/{id}/evidence", "application/json", request).await
    }
    /// POST /v1/chronology-rules
    pub async fn apply_rules(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ApplyRules", "POST", "/v1/chronology-rules", "text/yaml", request).await
    }
    /// GET /v1/chronology-rules/{name}
    pub async fn get_rules(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetRules", "GET", "/v1/chronology-rules/{name}", "application/json", request).await
    }
    /// GET /v1/claims/{claim_id}
    pub async fn get_claim(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetClaim", "GET", "/v1/claims/{claim_id}", "application/json", request).await
    }
    /// GET /v1/collections
    pub async fn list_collections(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ListCollections", "GET", "/v1/collections", "application/json", request).await
    }
    /// POST /v1/collections
    pub async fn create_collection(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("CreateCollection", "POST", "/v1/collections", "application/json", request).await
    }
    /// POST /v1/collections/{collection_id}/activate-index
    pub async fn activate_collection_index(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ActivateCollectionIndex", "POST", "/v1/collections/{collection_id}/activate-index", "application/json", request).await
    }
    /// GET /v1/collections/{id}
    pub async fn get_collection(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetCollection", "GET", "/v1/collections/{id}", "application/json", request).await
    }
    /// POST /v1/evidence
    pub async fn seal(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("Seal", "POST", "/v1/evidence", "application/json", request).await
    }
    /// DELETE /v1/evidence/{evidence_id}
    pub async fn purge(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("Purge", "DELETE", "/v1/evidence/{evidence_id}", "application/json", request).await
    }
    /// GET /v1/evidence/{evidence_id}
    pub async fn get_manifest(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetManifest", "GET", "/v1/evidence/{evidence_id}", "application/json", request).await
    }
    /// GET /v1/evidence/{evidence_id}/accesses
    pub async fn get_accesses(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetAccesses", "GET", "/v1/evidence/{evidence_id}/accesses", "application/json", request).await
    }
    /// PUT /v1/evidence/{evidence_id}/bytes
    pub async fn put_bytes(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("PutBytes", "PUT", "/v1/evidence/{evidence_id}/bytes", "application/octet-stream", request).await
    }
    /// POST /v1/evidence/{evidence_id}/commit
    pub async fn commit(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("Commit", "POST", "/v1/evidence/{evidence_id}/commit", "application/json", request).await
    }
    /// POST /v1/evidence/{evidence_id}/legal-hold
    pub async fn legal_hold(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("LegalHold", "POST", "/v1/evidence/{evidence_id}/legal-hold", "application/json", request).await
    }
    /// GET /v1/evidence/{evidence_id}/rows
    pub async fn get_rows(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetRows", "GET", "/v1/evidence/{evidence_id}/rows", "application/json", request).await
    }
    /// POST /v1/index-artifacts/backfill
    pub async fn backfill(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("Backfill", "POST", "/v1/index-artifacts/backfill", "application/json", request).await
    }
    /// GET /v1/index-artifacts/{index_version_id}
    pub async fn artifact_status(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ArtifactStatus", "GET", "/v1/index-artifacts/{index_version_id}", "application/json", request).await
    }
    /// POST /v1/index-artifacts/{index_version_id}/bind
    pub async fn bind_artifact(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("BindArtifact", "POST", "/v1/index-artifacts/{index_version_id}/bind", "application/json", request).await
    }
    /// POST /v1/index-artifacts/{index_version_id}/promote
    pub async fn promote_artifact(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("PromoteArtifact", "POST", "/v1/index-artifacts/{index_version_id}/promote", "application/json", request).await
    }
    /// POST /v1/index-artifacts/{index_version_id}/rebuild
    pub async fn rebuild_artifact(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("RebuildArtifact", "POST", "/v1/index-artifacts/{index_version_id}/rebuild", "application/json", request).await
    }
    /// POST /v1/index-artifacts/{index_version_id}/verify
    pub async fn verify_artifacts(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("VerifyArtifacts", "POST", "/v1/index-artifacts/{index_version_id}/verify", "application/json", request).await
    }
    /// GET /v1/index-build-jobs
    pub async fn list_jobs(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ListJobs", "GET", "/v1/index-build-jobs", "application/json", request).await
    }
    /// POST /v1/index-build-jobs
    pub async fn enqueue_job(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("EnqueueJob", "POST", "/v1/index-build-jobs", "application/json", request).await
    }
    /// GET /v1/index-build-jobs/{job_id}
    pub async fn get_job(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetJob", "GET", "/v1/index-build-jobs/{job_id}", "application/json", request).await
    }
    /// POST /v1/index-build-jobs/{job_id}/cancel
    pub async fn cancel_job(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("CancelJob", "POST", "/v1/index-build-jobs/{job_id}/cancel", "application/json", request).await
    }
    /// GET /v1/indexes/{shape_ref}
    pub async fn get_index(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetIndex", "GET", "/v1/indexes/{shape_ref}", "application/json", request).await
    }
    /// POST /v1/indexes/{shape_ref}/build
    pub async fn build_index(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("BuildIndex", "POST", "/v1/indexes/{shape_ref}/build", "application/json", request).await
    }
    /// POST /v1/ingest
    pub async fn ingest_file(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("IngestFile", "POST", "/v1/ingest", "application/json", request).await
    }
    /// POST /v1/ingest/batch
    pub async fn ingest_batch(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("IngestBatch", "POST", "/v1/ingest/batch", "application/json", request).await
    }
    /// POST /v1/ingest/bulk
    pub async fn bulk_open(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("BulkOpen", "POST", "/v1/ingest/bulk", "application/json", request).await
    }
    /// GET /v1/ingest/bulk/{bulk_id}
    pub async fn bulk_status(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("BulkStatus", "GET", "/v1/ingest/bulk/{bulk_id}", "application/json", request).await
    }
    /// POST /v1/ingest/bulk/{bulk_id}/chunk
    pub async fn bulk_chunk(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("BulkChunk", "POST", "/v1/ingest/bulk/{bulk_id}/chunk", "application/json", request).await
    }
    /// POST /v1/ingest/bulk/{bulk_id}/complete
    pub async fn bulk_complete(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("BulkComplete", "POST", "/v1/ingest/bulk/{bulk_id}/complete", "application/json", request).await
    }
    /// GET /v1/max-tokens
    pub async fn get_max_tokens(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetMaxTokens", "GET", "/v1/max-tokens", "application/json", request).await
    }
    /// POST /v1/max-tokens
    pub async fn replace_max_tokens(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ReplaceMaxTokens", "POST", "/v1/max-tokens", "application/json", request).await
    }
    /// POST /v1/monetary/observations
    pub async fn add_monetary_observation(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("AddMonetaryObservation", "POST", "/v1/monetary/observations", "application/json", request).await
    }
    /// GET /v1/monetary/prices
    pub async fn monetary_prices(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("MonetaryPrices", "GET", "/v1/monetary/prices", "application/json", request).await
    }
    /// POST /v1/monetary/prices
    pub async fn add_monetary_price(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("AddMonetaryPrice", "POST", "/v1/monetary/prices", "application/json", request).await
    }
    /// GET /v1/providers
    pub async fn list_providers(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ListProviders", "GET", "/v1/providers", "application/json", request).await
    }
    /// POST /v1/providers
    pub async fn apply_provider(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ApplyProvider", "POST", "/v1/providers", "text/yaml", request).await
    }
    /// POST /v1/providers/{name}/complete
    pub async fn provider_complete(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ProviderComplete", "POST", "/v1/providers/{name}/complete", "application/json", request).await
    }
    /// POST /v1/providers/{name}/embed
    pub async fn provider_embed(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ProviderEmbed", "POST", "/v1/providers/{name}/embed", "application/json", request).await
    }
    /// GET /v1/providers/{name}/health
    pub async fn provider_health(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ProviderHealth", "GET", "/v1/providers/{name}/health", "application/json", request).await
    }
    /// GET /v1/reports/audit
    pub async fn audit(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("Audit", "GET", "/v1/reports/audit", "application/json", request).await
    }
    /// GET /v1/reports/budget-usage
    pub async fn budget_usage_report(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("BudgetUsageReport", "GET", "/v1/reports/budget-usage", "application/json", request).await
    }
    /// GET /v1/reports/budgets
    pub async fn budgets(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("Budgets", "GET", "/v1/reports/budgets", "application/json", request).await
    }
    /// GET /v1/reports/cost
    pub async fn cost(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("Cost", "GET", "/v1/reports/cost", "application/json", request).await
    }
    /// GET /v1/reports/endpoints
    pub async fn endpoints(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("Endpoints", "GET", "/v1/reports/endpoints", "application/json", request).await
    }
    /// GET /v1/reports/evidence
    pub async fn evidence_report(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("EvidenceReport", "GET", "/v1/reports/evidence", "application/json", request).await
    }
    /// GET /v1/reports/matrix
    pub async fn matrix_report(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("MatrixReport", "GET", "/v1/reports/matrix", "application/json", request).await
    }
    /// GET /v1/reports/money
    pub async fn monetary_report(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("MonetaryReport", "GET", "/v1/reports/money", "application/json", request).await
    }
    /// GET /v1/reports/runbooks
    pub async fn runbook_report(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("RunbookReport", "GET", "/v1/reports/runbooks", "application/json", request).await
    }
    /// GET /v1/reports/sessions
    pub async fn sessions_report(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("SessionsReport", "GET", "/v1/reports/sessions", "application/json", request).await
    }
    /// GET /v1/reports/timeseries
    pub async fn timeseries(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("Timeseries", "GET", "/v1/reports/timeseries", "application/json", request).await
    }
    /// GET /v1/reports/usage
    pub async fn usage(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("Usage", "GET", "/v1/reports/usage", "application/json", request).await
    }
    /// PUT /v1/retrieval-rollout
    pub async fn rollout_set(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("RolloutSet", "PUT", "/v1/retrieval-rollout", "application/json", request).await
    }
    /// GET /v1/retrieval-rollout/{scope_kind}/{scope_id}
    pub async fn rollout_get(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("RolloutGet", "GET", "/v1/retrieval-rollout/{scope_kind}/{scope_id}", "application/json", request).await
    }
    /// GET /v1/runbooks
    pub async fn list_runbooks(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ListRunbooks", "GET", "/v1/runbooks", "application/json", request).await
    }
    /// POST /v1/runbooks
    pub async fn apply_runbook(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ApplyRunbook", "POST", "/v1/runbooks", "text/yaml", request).await
    }
    /// POST /v1/runbooks/validate
    pub async fn validate_runbook(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ValidateRunbook", "POST", "/v1/runbooks/validate", "text/yaml", request).await
    }
    /// GET /v1/runbooks/{name}
    pub async fn get_runbook_info(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetRunbookInfo", "GET", "/v1/runbooks/{name}", "application/json", request).await
    }
    /// POST /v1/runbooks/{name}/remove-confirm
    pub async fn remove_confirm(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("RemoveConfirm", "POST", "/v1/runbooks/{name}/remove-confirm", "application/json", request).await
    }
    /// POST /v1/runbooks/{name}/remove-request
    pub async fn remove_request(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("RemoveRequest", "POST", "/v1/runbooks/{name}/remove-request", "application/json", request).await
    }
    /// POST /v1/runbooks/{name}/runs
    pub async fn run_runbook(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("RunRunbook", "POST", "/v1/runbooks/{name}/runs", "application/json", request).await
    }
    /// POST /v1/runbooks/{name}/sessions
    pub async fn create_session(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("CreateSession", "POST", "/v1/runbooks/{name}/sessions", "application/json", request).await
    }
    /// GET /v1/runs/{run_id}
    pub async fn get_run(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetRun", "GET", "/v1/runs/{run_id}", "application/json", request).await
    }
    /// POST /v1/runs/{run_id}/steps/{ordinal}/approve
    pub async fn approve_step(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ApproveStep", "POST", "/v1/runs/{run_id}/steps/{ordinal}/approve", "application/json", request).await
    }
    /// POST /v1/search
    pub async fn hybrid_search(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("HybridSearch", "POST", "/v1/search", "application/json", request).await
    }
    /// GET /v1/sessions/{id}
    pub async fn get_session(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetSession", "GET", "/v1/sessions/{id}", "application/json", request).await
    }
    /// POST /v1/sessions/{id}/close
    pub async fn close_session(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("CloseSession", "POST", "/v1/sessions/{id}/close", "application/json", request).await
    }
    /// POST /v1/sessions/{id}/turns
    pub async fn turn(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("Turn", "POST", "/v1/sessions/{id}/turns", "application/json", request).await
    }
    /// POST /v1/sessions/{id}/turns/stream
    pub async fn turn_stream(&self, request: ApiRequest) -> Result<ApiStream> {
        self.stream("TurnStream", "POST", "/v1/sessions/{id}/turns/stream", "application/json", request).await
    }
    /// POST /v1/shapes
    pub async fn apply_shape(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ApplyShape", "POST", "/v1/shapes", "text/yaml", request).await
    }
    /// PUT /v1/sources
    pub async fn put_source(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("PutSource", "PUT", "/v1/sources", "application/octet-stream", request).await
    }
    /// GET /v1/sources/{source_id}
    pub async fn get_source(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetSource", "GET", "/v1/sources/{source_id}", "application/json", request).await
    }
    /// POST /v1/versions
    pub async fn create_version(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("CreateVersion", "POST", "/v1/versions", "application/json", request).await
    }
    /// GET /v1/versions/{version_id}/anchors
    pub async fn get_anchors(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetAnchors", "GET", "/v1/versions/{version_id}/anchors", "application/json", request).await
    }
    /// POST /v1/versions/{version_id}/anchors
    pub async fn lock_anchor(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("LockAnchor", "POST", "/v1/versions/{version_id}/anchors", "application/json", request).await
    }
    /// POST /v1/versions/{version_id}/claims
    pub async fn propose_claim(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("ProposeClaim", "POST", "/v1/versions/{version_id}/claims", "application/json", request).await
    }
    /// GET /v1/versions/{version_id}/context
    pub async fn get_context(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetContext", "GET", "/v1/versions/{version_id}/context", "application/json", request).await
    }
    /// GET /v1/versions/{version_id}/counters
    pub async fn get_counters(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetCounters", "GET", "/v1/versions/{version_id}/counters", "application/json", request).await
    }
    /// POST /v1/versions/{version_id}/counters
    pub async fn record_counts(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("RecordCounts", "POST", "/v1/versions/{version_id}/counters", "application/json", request).await
    }
    /// GET /v1/versions/{version_id}/digests
    pub async fn get_digests(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetDigests", "GET", "/v1/versions/{version_id}/digests", "application/json", request).await
    }
    /// PUT /v1/versions/{version_id}/digests
    pub async fn upsert_digest(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("UpsertDigest", "PUT", "/v1/versions/{version_id}/digests", "application/json", request).await
    }
    /// POST /v1/versions/{version_id}/events
    pub async fn append_events(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("AppendEvents", "POST", "/v1/versions/{version_id}/events", "application/json", request).await
    }
    /// GET /v1/versions/{version_id}/facts
    pub async fn get_facts(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetFacts", "GET", "/v1/versions/{version_id}/facts", "application/json", request).await
    }
    /// GET /v1/versions/{version_id}/findings
    pub async fn get_findings(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetFindings", "GET", "/v1/versions/{version_id}/findings", "application/json", request).await
    }
    /// POST /v1/versions/{version_id}/findings
    pub async fn record_findings(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("RecordFindings", "POST", "/v1/versions/{version_id}/findings", "application/json", request).await
    }
    /// GET /v1/versions/{version_id}/head
    pub async fn get_head(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetHead", "GET", "/v1/versions/{version_id}/head", "application/json", request).await
    }
    /// POST /v1/versions/{version_id}/ingests
    pub async fn record_ingest(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("RecordIngest", "POST", "/v1/versions/{version_id}/ingests", "application/json", request).await
    }
    /// GET /v1/versions/{version_id}/lineage
    pub async fn get_lineage(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetLineage", "GET", "/v1/versions/{version_id}/lineage", "application/json", request).await
    }
    /// GET /v1/versions/{version_id}/promises
    pub async fn get_promises(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("GetPromises", "GET", "/v1/versions/{version_id}/promises", "application/json", request).await
    }
    /// POST /v1/versions/{version_id}/promises
    pub async fn open_promise(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("OpenPromise", "POST", "/v1/versions/{version_id}/promises", "application/json", request).await
    }
    /// POST /v1/versions/{version_id}/promises/{key}/fulfill
    pub async fn fulfill_promise(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("FulfillPromise", "POST", "/v1/versions/{version_id}/promises/{key}/fulfill", "application/json", request).await
    }
    /// GET /version
    pub async fn version_info(&self, request: ApiRequest) -> Result<ApiResponse> {
        self.call("VersionInfo", "GET", "/version", "application/json", request).await
    }
}
