# SPDX-License-Identifier: Apache-2.0
# Generated by scripts/generate_server_api.py; payload schemas are in OpenAPI.
from __future__ import annotations

from collections.abc import AsyncIterator, Iterator

from ._server_api import ApiRequest, ApiResponse, BaseAsyncServerApi, BaseServerApi


class ServerApiClient(BaseServerApi):
    def healthai(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /healthai"""
        return self._call(
            "Healthai",
            "GET",
            "/healthai",
            "application/json",
            request,
        )

    def healthz(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /healthz"""
        return self._call(
            "Healthz",
            "GET",
            "/healthz",
            "application/json",
            request,
        )

    def openapi_json(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /openapi.json"""
        return self._call(
            "OpenapiJson",
            "GET",
            "/openapi.json",
            "application/json",
            request,
        )

    def readyz(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /readyz"""
        return self._call(
            "Readyz",
            "GET",
            "/readyz",
            "application/json",
            request,
        )

    def compose_answer(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1.2/answers"""
        return self._call(
            "ComposeAnswer",
            "POST",
            "/v1.2/answers",
            "application/json",
            request,
        )

    def get_collection_governance(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1.2/collections/{id}/governance"""
        return self._call(
            "GetCollectionGovernance",
            "GET",
            "/v1.2/collections/{id}/governance",
            "application/json",
            request,
        )

    def replace_collection_governance(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """PUT /v1.2/collections/{id}/governance"""
        return self._call(
            "ReplaceCollectionGovernance",
            "PUT",
            "/v1.2/collections/{id}/governance",
            "application/json",
            request,
        )

    def authorize_publication(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1.2/collections/{id}/publications/{publication_id}"""
        return self._call(
            "AuthorizePublication",
            "GET",
            "/v1.2/collections/{id}/publications/{publication_id}",
            "application/json",
            request,
        )

    def get_collection_vocabulary(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1.2/collections/{id}/vocabulary"""
        return self._call(
            "GetCollectionVocabulary",
            "GET",
            "/v1.2/collections/{id}/vocabulary",
            "application/json",
            request,
        )

    def update_collection_vocabulary(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """PATCH /v1.2/collections/{id}/vocabulary"""
        return self._call(
            "UpdateCollectionVocabulary",
            "PATCH",
            "/v1.2/collections/{id}/vocabulary",
            "application/json",
            request,
        )

    def replace_collection_vocabulary(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """PUT /v1.2/collections/{id}/vocabulary"""
        return self._call(
            "ReplaceCollectionVocabulary",
            "PUT",
            "/v1.2/collections/{id}/vocabulary",
            "application/json",
            request,
        )

    def refresh_collection_vocabulary(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1.2/collections/{id}/vocabulary/refresh"""
        return self._call(
            "RefreshCollectionVocabulary",
            "POST",
            "/v1.2/collections/{id}/vocabulary/refresh",
            "application/json",
            request,
        )

    def get_vocabulary_revision(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1.2/collections/{id}/vocabulary/revision"""
        return self._call(
            "GetVocabularyRevision",
            "GET",
            "/v1.2/collections/{id}/vocabulary/revision",
            "application/json",
            request,
        )

    def query_collections(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1.2/query"""
        return self._call(
            "QueryCollections",
            "POST",
            "/v1.2/query",
            "application/json",
            request,
        )

    def search_collection(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1.2/search"""
        return self._call(
            "SearchCollection",
            "POST",
            "/v1.2/search",
            "application/json",
            request,
        )

    def get_vocabulary_settings(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1.2/vocabulary-settings"""
        return self._call(
            "GetVocabularySettings",
            "GET",
            "/v1.2/vocabulary-settings",
            "application/json",
            request,
        )

    def replace_vocabulary_settings(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """PUT /v1.2/vocabulary-settings"""
        return self._call(
            "ReplaceVocabularySettings",
            "PUT",
            "/v1.2/vocabulary-settings",
            "application/json",
            request,
        )

    def list_tokens(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/access-tokens"""
        return self._call(
            "ListTokens",
            "GET",
            "/v1/access-tokens",
            "application/json",
            request,
        )

    def issue_access_token(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/access-tokens"""
        return self._call(
            "IssueAccessToken",
            "POST",
            "/v1/access-tokens",
            "application/json",
            request,
        )

    def revoke_token(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/access-tokens/{jti}/revoke"""
        return self._call(
            "RevokeToken",
            "POST",
            "/v1/access-tokens/{jti}/revoke",
            "application/json",
            request,
        )

    def list_drafts(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/authoring/drafts"""
        return self._call(
            "ListDrafts",
            "GET",
            "/v1/authoring/drafts",
            "application/json",
            request,
        )

    def create_draft(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/authoring/drafts"""
        return self._call(
            "CreateDraft",
            "POST",
            "/v1/authoring/drafts",
            "application/json",
            request,
        )

    def delete_draft(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """DELETE /v1/authoring/drafts/{draft_id}"""
        return self._call(
            "DeleteDraft",
            "DELETE",
            "/v1/authoring/drafts/{draft_id}",
            "application/json",
            request,
        )

    def get_draft(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/authoring/drafts/{draft_id}"""
        return self._call(
            "GetDraft",
            "GET",
            "/v1/authoring/drafts/{draft_id}",
            "application/json",
            request,
        )

    def update_answers(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """PUT /v1/authoring/drafts/{draft_id}/answers"""
        return self._call(
            "UpdateAnswers",
            "PUT",
            "/v1/authoring/drafts/{draft_id}/answers",
            "application/json",
            request,
        )

    def apply_draft(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/authoring/drafts/{draft_id}/apply"""
        return self._call(
            "ApplyDraft",
            "POST",
            "/v1/authoring/drafts/{draft_id}/apply",
            "application/json",
            request,
        )

    def assist_draft(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/authoring/drafts/{draft_id}/assist"""
        return self._call(
            "AssistDraft",
            "POST",
            "/v1/authoring/drafts/{draft_id}/assist",
            "application/json",
            request,
        )

    def export_draft(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/authoring/drafts/{draft_id}/export"""
        return self._call(
            "ExportDraft",
            "POST",
            "/v1/authoring/drafts/{draft_id}/export",
            "application/json",
            request,
        )

    def validate_draft(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/authoring/drafts/{draft_id}/validate"""
        return self._call(
            "ValidateDraft",
            "POST",
            "/v1/authoring/drafts/{draft_id}/validate",
            "application/json",
            request,
        )

    def list_patterns(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/authoring/patterns"""
        return self._call(
            "ListPatterns",
            "GET",
            "/v1/authoring/patterns",
            "application/json",
            request,
        )

    def get_pattern(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/authoring/patterns/{id}"""
        return self._call(
            "GetPattern",
            "GET",
            "/v1/authoring/patterns/{id}",
            "application/json",
            request,
        )

    def budget_adjustments(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/budgets/{id}/adjustments"""
        return self._call(
            "BudgetAdjustments",
            "GET",
            "/v1/budgets/{id}/adjustments",
            "application/json",
            request,
        )

    def reconcile_budget(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/budgets/{id}/adjustments"""
        return self._call(
            "ReconcileBudget",
            "POST",
            "/v1/budgets/{id}/adjustments",
            "application/json",
            request,
        )

    def budget_evidence(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/budgets/{id}/evidence"""
        return self._call(
            "BudgetEvidence",
            "GET",
            "/v1/budgets/{id}/evidence",
            "application/json",
            request,
        )

    def apply_rules(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/chronology-rules"""
        return self._call(
            "ApplyRules",
            "POST",
            "/v1/chronology-rules",
            "text/yaml",
            request,
        )

    def get_rules(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/chronology-rules/{name}"""
        return self._call(
            "GetRules",
            "GET",
            "/v1/chronology-rules/{name}",
            "application/json",
            request,
        )

    def get_claim(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/claims/{claim_id}"""
        return self._call(
            "GetClaim",
            "GET",
            "/v1/claims/{claim_id}",
            "application/json",
            request,
        )

    def list_collections(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/collections"""
        return self._call(
            "ListCollections",
            "GET",
            "/v1/collections",
            "application/json",
            request,
        )

    def create_collection(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/collections"""
        return self._call(
            "CreateCollection",
            "POST",
            "/v1/collections",
            "application/json",
            request,
        )

    def activate_collection_index(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/collections/{collection_id}/activate-index"""
        return self._call(
            "ActivateCollectionIndex",
            "POST",
            "/v1/collections/{collection_id}/activate-index",
            "application/json",
            request,
        )

    def get_collection(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/collections/{id}"""
        return self._call(
            "GetCollection",
            "GET",
            "/v1/collections/{id}",
            "application/json",
            request,
        )

    def seal(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/evidence"""
        return self._call(
            "Seal",
            "POST",
            "/v1/evidence",
            "application/json",
            request,
        )

    def purge(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """DELETE /v1/evidence/{evidence_id}"""
        return self._call(
            "Purge",
            "DELETE",
            "/v1/evidence/{evidence_id}",
            "application/json",
            request,
        )

    def get_manifest(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/evidence/{evidence_id}"""
        return self._call(
            "GetManifest",
            "GET",
            "/v1/evidence/{evidence_id}",
            "application/json",
            request,
        )

    def get_accesses(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/evidence/{evidence_id}/accesses"""
        return self._call(
            "GetAccesses",
            "GET",
            "/v1/evidence/{evidence_id}/accesses",
            "application/json",
            request,
        )

    def put_bytes(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """PUT /v1/evidence/{evidence_id}/bytes"""
        return self._call(
            "PutBytes",
            "PUT",
            "/v1/evidence/{evidence_id}/bytes",
            "application/octet-stream",
            request,
        )

    def commit(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/evidence/{evidence_id}/commit"""
        return self._call(
            "Commit",
            "POST",
            "/v1/evidence/{evidence_id}/commit",
            "application/json",
            request,
        )

    def legal_hold(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/evidence/{evidence_id}/legal-hold"""
        return self._call(
            "LegalHold",
            "POST",
            "/v1/evidence/{evidence_id}/legal-hold",
            "application/json",
            request,
        )

    def get_rows(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/evidence/{evidence_id}/rows"""
        return self._call(
            "GetRows",
            "GET",
            "/v1/evidence/{evidence_id}/rows",
            "application/json",
            request,
        )

    def backfill(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/index-artifacts/backfill"""
        return self._call(
            "Backfill",
            "POST",
            "/v1/index-artifacts/backfill",
            "application/json",
            request,
        )

    def artifact_status(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/index-artifacts/{index_version_id}"""
        return self._call(
            "ArtifactStatus",
            "GET",
            "/v1/index-artifacts/{index_version_id}",
            "application/json",
            request,
        )

    def bind_artifact(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/index-artifacts/{index_version_id}/bind"""
        return self._call(
            "BindArtifact",
            "POST",
            "/v1/index-artifacts/{index_version_id}/bind",
            "application/json",
            request,
        )

    def promote_artifact(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/index-artifacts/{index_version_id}/promote"""
        return self._call(
            "PromoteArtifact",
            "POST",
            "/v1/index-artifacts/{index_version_id}/promote",
            "application/json",
            request,
        )

    def rebuild_artifact(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/index-artifacts/{index_version_id}/rebuild"""
        return self._call(
            "RebuildArtifact",
            "POST",
            "/v1/index-artifacts/{index_version_id}/rebuild",
            "application/json",
            request,
        )

    def verify_artifacts(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/index-artifacts/{index_version_id}/verify"""
        return self._call(
            "VerifyArtifacts",
            "POST",
            "/v1/index-artifacts/{index_version_id}/verify",
            "application/json",
            request,
        )

    def list_jobs(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/index-build-jobs"""
        return self._call(
            "ListJobs",
            "GET",
            "/v1/index-build-jobs",
            "application/json",
            request,
        )

    def enqueue_job(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/index-build-jobs"""
        return self._call(
            "EnqueueJob",
            "POST",
            "/v1/index-build-jobs",
            "application/json",
            request,
        )

    def get_job(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/index-build-jobs/{job_id}"""
        return self._call(
            "GetJob",
            "GET",
            "/v1/index-build-jobs/{job_id}",
            "application/json",
            request,
        )

    def cancel_job(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/index-build-jobs/{job_id}/cancel"""
        return self._call(
            "CancelJob",
            "POST",
            "/v1/index-build-jobs/{job_id}/cancel",
            "application/json",
            request,
        )

    def get_index(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/indexes/{shape_ref}"""
        return self._call(
            "GetIndex",
            "GET",
            "/v1/indexes/{shape_ref}",
            "application/json",
            request,
        )

    def build_index(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/indexes/{shape_ref}/build"""
        return self._call(
            "BuildIndex",
            "POST",
            "/v1/indexes/{shape_ref}/build",
            "application/json",
            request,
        )

    def ingest_file(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/ingest"""
        return self._call(
            "IngestFile",
            "POST",
            "/v1/ingest",
            "application/json",
            request,
        )

    def ingest_batch(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/ingest/batch"""
        return self._call(
            "IngestBatch",
            "POST",
            "/v1/ingest/batch",
            "application/json",
            request,
        )

    def bulk_open(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/ingest/bulk"""
        return self._call(
            "BulkOpen",
            "POST",
            "/v1/ingest/bulk",
            "application/json",
            request,
        )

    def bulk_status(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/ingest/bulk/{bulk_id}"""
        return self._call(
            "BulkStatus",
            "GET",
            "/v1/ingest/bulk/{bulk_id}",
            "application/json",
            request,
        )

    def bulk_chunk(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/ingest/bulk/{bulk_id}/chunk"""
        return self._call(
            "BulkChunk",
            "POST",
            "/v1/ingest/bulk/{bulk_id}/chunk",
            "application/json",
            request,
        )

    def bulk_complete(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/ingest/bulk/{bulk_id}/complete"""
        return self._call(
            "BulkComplete",
            "POST",
            "/v1/ingest/bulk/{bulk_id}/complete",
            "application/json",
            request,
        )

    def get_max_tokens(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/max-tokens"""
        return self._call(
            "GetMaxTokens",
            "GET",
            "/v1/max-tokens",
            "application/json",
            request,
        )

    def replace_max_tokens(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/max-tokens"""
        return self._call(
            "ReplaceMaxTokens",
            "POST",
            "/v1/max-tokens",
            "application/json",
            request,
        )

    def add_monetary_observation(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/monetary/observations"""
        return self._call(
            "AddMonetaryObservation",
            "POST",
            "/v1/monetary/observations",
            "application/json",
            request,
        )

    def monetary_prices(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/monetary/prices"""
        return self._call(
            "MonetaryPrices",
            "GET",
            "/v1/monetary/prices",
            "application/json",
            request,
        )

    def add_monetary_price(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/monetary/prices"""
        return self._call(
            "AddMonetaryPrice",
            "POST",
            "/v1/monetary/prices",
            "application/json",
            request,
        )

    def list_providers(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/providers"""
        return self._call(
            "ListProviders",
            "GET",
            "/v1/providers",
            "application/json",
            request,
        )

    def apply_provider(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/providers"""
        return self._call(
            "ApplyProvider",
            "POST",
            "/v1/providers",
            "text/yaml",
            request,
        )

    def provider_complete(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/providers/{name}/complete"""
        return self._call(
            "ProviderComplete",
            "POST",
            "/v1/providers/{name}/complete",
            "application/json",
            request,
        )

    def provider_embed(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/providers/{name}/embed"""
        return self._call(
            "ProviderEmbed",
            "POST",
            "/v1/providers/{name}/embed",
            "application/json",
            request,
        )

    def provider_health(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/providers/{name}/health"""
        return self._call(
            "ProviderHealth",
            "GET",
            "/v1/providers/{name}/health",
            "application/json",
            request,
        )

    def audit(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/audit"""
        return self._call(
            "Audit",
            "GET",
            "/v1/reports/audit",
            "application/json",
            request,
        )

    def budget_usage_report(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/budget-usage"""
        return self._call(
            "BudgetUsageReport",
            "GET",
            "/v1/reports/budget-usage",
            "application/json",
            request,
        )

    def budgets(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/budgets"""
        return self._call(
            "Budgets",
            "GET",
            "/v1/reports/budgets",
            "application/json",
            request,
        )

    def cost(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/cost"""
        return self._call(
            "Cost",
            "GET",
            "/v1/reports/cost",
            "application/json",
            request,
        )

    def endpoints(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/endpoints"""
        return self._call(
            "Endpoints",
            "GET",
            "/v1/reports/endpoints",
            "application/json",
            request,
        )

    def evidence_report(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/evidence"""
        return self._call(
            "EvidenceReport",
            "GET",
            "/v1/reports/evidence",
            "application/json",
            request,
        )

    def matrix_report(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/matrix"""
        return self._call(
            "MatrixReport",
            "GET",
            "/v1/reports/matrix",
            "application/json",
            request,
        )

    def monetary_report(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/money"""
        return self._call(
            "MonetaryReport",
            "GET",
            "/v1/reports/money",
            "application/json",
            request,
        )

    def runbook_report(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/runbooks"""
        return self._call(
            "RunbookReport",
            "GET",
            "/v1/reports/runbooks",
            "application/json",
            request,
        )

    def sessions_report(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/sessions"""
        return self._call(
            "SessionsReport",
            "GET",
            "/v1/reports/sessions",
            "application/json",
            request,
        )

    def timeseries(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/timeseries"""
        return self._call(
            "Timeseries",
            "GET",
            "/v1/reports/timeseries",
            "application/json",
            request,
        )

    def usage(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/usage"""
        return self._call(
            "Usage",
            "GET",
            "/v1/reports/usage",
            "application/json",
            request,
        )

    def rollout_set(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """PUT /v1/retrieval-rollout"""
        return self._call(
            "RolloutSet",
            "PUT",
            "/v1/retrieval-rollout",
            "application/json",
            request,
        )

    def rollout_get(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/retrieval-rollout/{scope_kind}/{scope_id}"""
        return self._call(
            "RolloutGet",
            "GET",
            "/v1/retrieval-rollout/{scope_kind}/{scope_id}",
            "application/json",
            request,
        )

    def list_runbooks(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/runbooks"""
        return self._call(
            "ListRunbooks",
            "GET",
            "/v1/runbooks",
            "application/json",
            request,
        )

    def apply_runbook(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/runbooks"""
        return self._call(
            "ApplyRunbook",
            "POST",
            "/v1/runbooks",
            "text/yaml",
            request,
        )

    def validate_runbook(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/runbooks/validate"""
        return self._call(
            "ValidateRunbook",
            "POST",
            "/v1/runbooks/validate",
            "text/yaml",
            request,
        )

    def get_runbook_info(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/runbooks/{name}"""
        return self._call(
            "GetRunbookInfo",
            "GET",
            "/v1/runbooks/{name}",
            "application/json",
            request,
        )

    def remove_confirm(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/runbooks/{name}/remove-confirm"""
        return self._call(
            "RemoveConfirm",
            "POST",
            "/v1/runbooks/{name}/remove-confirm",
            "application/json",
            request,
        )

    def remove_request(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/runbooks/{name}/remove-request"""
        return self._call(
            "RemoveRequest",
            "POST",
            "/v1/runbooks/{name}/remove-request",
            "application/json",
            request,
        )

    def run_runbook(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/runbooks/{name}/runs"""
        return self._call(
            "RunRunbook",
            "POST",
            "/v1/runbooks/{name}/runs",
            "application/json",
            request,
        )

    def create_session(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/runbooks/{name}/sessions"""
        return self._call(
            "CreateSession",
            "POST",
            "/v1/runbooks/{name}/sessions",
            "application/json",
            request,
        )

    def get_run(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/runs/{run_id}"""
        return self._call(
            "GetRun",
            "GET",
            "/v1/runs/{run_id}",
            "application/json",
            request,
        )

    def approve_step(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/runs/{run_id}/steps/{ordinal}/approve"""
        return self._call(
            "ApproveStep",
            "POST",
            "/v1/runs/{run_id}/steps/{ordinal}/approve",
            "application/json",
            request,
        )

    def hybrid_search(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/search"""
        return self._call(
            "HybridSearch",
            "POST",
            "/v1/search",
            "application/json",
            request,
        )

    def get_session(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/sessions/{id}"""
        return self._call(
            "GetSession",
            "GET",
            "/v1/sessions/{id}",
            "application/json",
            request,
        )

    def close_session(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/sessions/{id}/close"""
        return self._call(
            "CloseSession",
            "POST",
            "/v1/sessions/{id}/close",
            "application/json",
            request,
        )

    def turn(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/sessions/{id}/turns"""
        return self._call(
            "Turn",
            "POST",
            "/v1/sessions/{id}/turns",
            "application/json",
            request,
        )

    def turn_stream(
        self,
        request: ApiRequest | None = None,
    ) -> Iterator[ApiResponse]:
        """POST /v1/sessions/{id}/turns/stream"""
        return self._stream(
            "TurnStream",
            "POST",
            "/v1/sessions/{id}/turns/stream",
            "application/json",
            request,
        )

    def apply_shape(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/shapes"""
        return self._call(
            "ApplyShape",
            "POST",
            "/v1/shapes",
            "text/yaml",
            request,
        )

    def put_source(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """PUT /v1/sources"""
        return self._call(
            "PutSource",
            "PUT",
            "/v1/sources",
            "application/octet-stream",
            request,
        )

    def get_source(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/sources/{source_id}"""
        return self._call(
            "GetSource",
            "GET",
            "/v1/sources/{source_id}",
            "application/json",
            request,
        )

    def create_version(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/versions"""
        return self._call(
            "CreateVersion",
            "POST",
            "/v1/versions",
            "application/json",
            request,
        )

    def get_anchors(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/versions/{version_id}/anchors"""
        return self._call(
            "GetAnchors",
            "GET",
            "/v1/versions/{version_id}/anchors",
            "application/json",
            request,
        )

    def lock_anchor(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/versions/{version_id}/anchors"""
        return self._call(
            "LockAnchor",
            "POST",
            "/v1/versions/{version_id}/anchors",
            "application/json",
            request,
        )

    def propose_claim(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/versions/{version_id}/claims"""
        return self._call(
            "ProposeClaim",
            "POST",
            "/v1/versions/{version_id}/claims",
            "application/json",
            request,
        )

    def get_context(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/versions/{version_id}/context"""
        return self._call(
            "GetContext",
            "GET",
            "/v1/versions/{version_id}/context",
            "application/json",
            request,
        )

    def get_counters(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/versions/{version_id}/counters"""
        return self._call(
            "GetCounters",
            "GET",
            "/v1/versions/{version_id}/counters",
            "application/json",
            request,
        )

    def record_counts(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/versions/{version_id}/counters"""
        return self._call(
            "RecordCounts",
            "POST",
            "/v1/versions/{version_id}/counters",
            "application/json",
            request,
        )

    def get_digests(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/versions/{version_id}/digests"""
        return self._call(
            "GetDigests",
            "GET",
            "/v1/versions/{version_id}/digests",
            "application/json",
            request,
        )

    def upsert_digest(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """PUT /v1/versions/{version_id}/digests"""
        return self._call(
            "UpsertDigest",
            "PUT",
            "/v1/versions/{version_id}/digests",
            "application/json",
            request,
        )

    def append_events(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/versions/{version_id}/events"""
        return self._call(
            "AppendEvents",
            "POST",
            "/v1/versions/{version_id}/events",
            "application/json",
            request,
        )

    def get_facts(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/versions/{version_id}/facts"""
        return self._call(
            "GetFacts",
            "GET",
            "/v1/versions/{version_id}/facts",
            "application/json",
            request,
        )

    def get_findings(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/versions/{version_id}/findings"""
        return self._call(
            "GetFindings",
            "GET",
            "/v1/versions/{version_id}/findings",
            "application/json",
            request,
        )

    def record_findings(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/versions/{version_id}/findings"""
        return self._call(
            "RecordFindings",
            "POST",
            "/v1/versions/{version_id}/findings",
            "application/json",
            request,
        )

    def get_head(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/versions/{version_id}/head"""
        return self._call(
            "GetHead",
            "GET",
            "/v1/versions/{version_id}/head",
            "application/json",
            request,
        )

    def record_ingest(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/versions/{version_id}/ingests"""
        return self._call(
            "RecordIngest",
            "POST",
            "/v1/versions/{version_id}/ingests",
            "application/json",
            request,
        )

    def get_lineage(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/versions/{version_id}/lineage"""
        return self._call(
            "GetLineage",
            "GET",
            "/v1/versions/{version_id}/lineage",
            "application/json",
            request,
        )

    def get_promises(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/versions/{version_id}/promises"""
        return self._call(
            "GetPromises",
            "GET",
            "/v1/versions/{version_id}/promises",
            "application/json",
            request,
        )

    def open_promise(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/versions/{version_id}/promises"""
        return self._call(
            "OpenPromise",
            "POST",
            "/v1/versions/{version_id}/promises",
            "application/json",
            request,
        )

    def fulfill_promise(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/versions/{version_id}/promises/{key}/fulfill"""
        return self._call(
            "FulfillPromise",
            "POST",
            "/v1/versions/{version_id}/promises/{key}/fulfill",
            "application/json",
            request,
        )

    def version_info(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /version"""
        return self._call(
            "VersionInfo",
            "GET",
            "/version",
            "application/json",
            request,
        )


class AsyncServerApiClient(BaseAsyncServerApi):
    async def healthai(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /healthai"""
        return await self._call(
            "Healthai",
            "GET",
            "/healthai",
            "application/json",
            request,
        )

    async def healthz(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /healthz"""
        return await self._call(
            "Healthz",
            "GET",
            "/healthz",
            "application/json",
            request,
        )

    async def openapi_json(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /openapi.json"""
        return await self._call(
            "OpenapiJson",
            "GET",
            "/openapi.json",
            "application/json",
            request,
        )

    async def readyz(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /readyz"""
        return await self._call(
            "Readyz",
            "GET",
            "/readyz",
            "application/json",
            request,
        )

    async def compose_answer(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1.2/answers"""
        return await self._call(
            "ComposeAnswer",
            "POST",
            "/v1.2/answers",
            "application/json",
            request,
        )

    async def get_collection_governance(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1.2/collections/{id}/governance"""
        return await self._call(
            "GetCollectionGovernance",
            "GET",
            "/v1.2/collections/{id}/governance",
            "application/json",
            request,
        )

    async def replace_collection_governance(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """PUT /v1.2/collections/{id}/governance"""
        return await self._call(
            "ReplaceCollectionGovernance",
            "PUT",
            "/v1.2/collections/{id}/governance",
            "application/json",
            request,
        )

    async def authorize_publication(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1.2/collections/{id}/publications/{publication_id}"""
        return await self._call(
            "AuthorizePublication",
            "GET",
            "/v1.2/collections/{id}/publications/{publication_id}",
            "application/json",
            request,
        )

    async def get_collection_vocabulary(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1.2/collections/{id}/vocabulary"""
        return await self._call(
            "GetCollectionVocabulary",
            "GET",
            "/v1.2/collections/{id}/vocabulary",
            "application/json",
            request,
        )

    async def update_collection_vocabulary(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """PATCH /v1.2/collections/{id}/vocabulary"""
        return await self._call(
            "UpdateCollectionVocabulary",
            "PATCH",
            "/v1.2/collections/{id}/vocabulary",
            "application/json",
            request,
        )

    async def replace_collection_vocabulary(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """PUT /v1.2/collections/{id}/vocabulary"""
        return await self._call(
            "ReplaceCollectionVocabulary",
            "PUT",
            "/v1.2/collections/{id}/vocabulary",
            "application/json",
            request,
        )

    async def refresh_collection_vocabulary(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1.2/collections/{id}/vocabulary/refresh"""
        return await self._call(
            "RefreshCollectionVocabulary",
            "POST",
            "/v1.2/collections/{id}/vocabulary/refresh",
            "application/json",
            request,
        )

    async def get_vocabulary_revision(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1.2/collections/{id}/vocabulary/revision"""
        return await self._call(
            "GetVocabularyRevision",
            "GET",
            "/v1.2/collections/{id}/vocabulary/revision",
            "application/json",
            request,
        )

    async def query_collections(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1.2/query"""
        return await self._call(
            "QueryCollections",
            "POST",
            "/v1.2/query",
            "application/json",
            request,
        )

    async def search_collection(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1.2/search"""
        return await self._call(
            "SearchCollection",
            "POST",
            "/v1.2/search",
            "application/json",
            request,
        )

    async def get_vocabulary_settings(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1.2/vocabulary-settings"""
        return await self._call(
            "GetVocabularySettings",
            "GET",
            "/v1.2/vocabulary-settings",
            "application/json",
            request,
        )

    async def replace_vocabulary_settings(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """PUT /v1.2/vocabulary-settings"""
        return await self._call(
            "ReplaceVocabularySettings",
            "PUT",
            "/v1.2/vocabulary-settings",
            "application/json",
            request,
        )

    async def list_tokens(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/access-tokens"""
        return await self._call(
            "ListTokens",
            "GET",
            "/v1/access-tokens",
            "application/json",
            request,
        )

    async def issue_access_token(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/access-tokens"""
        return await self._call(
            "IssueAccessToken",
            "POST",
            "/v1/access-tokens",
            "application/json",
            request,
        )

    async def revoke_token(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/access-tokens/{jti}/revoke"""
        return await self._call(
            "RevokeToken",
            "POST",
            "/v1/access-tokens/{jti}/revoke",
            "application/json",
            request,
        )

    async def list_drafts(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/authoring/drafts"""
        return await self._call(
            "ListDrafts",
            "GET",
            "/v1/authoring/drafts",
            "application/json",
            request,
        )

    async def create_draft(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/authoring/drafts"""
        return await self._call(
            "CreateDraft",
            "POST",
            "/v1/authoring/drafts",
            "application/json",
            request,
        )

    async def delete_draft(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """DELETE /v1/authoring/drafts/{draft_id}"""
        return await self._call(
            "DeleteDraft",
            "DELETE",
            "/v1/authoring/drafts/{draft_id}",
            "application/json",
            request,
        )

    async def get_draft(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/authoring/drafts/{draft_id}"""
        return await self._call(
            "GetDraft",
            "GET",
            "/v1/authoring/drafts/{draft_id}",
            "application/json",
            request,
        )

    async def update_answers(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """PUT /v1/authoring/drafts/{draft_id}/answers"""
        return await self._call(
            "UpdateAnswers",
            "PUT",
            "/v1/authoring/drafts/{draft_id}/answers",
            "application/json",
            request,
        )

    async def apply_draft(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/authoring/drafts/{draft_id}/apply"""
        return await self._call(
            "ApplyDraft",
            "POST",
            "/v1/authoring/drafts/{draft_id}/apply",
            "application/json",
            request,
        )

    async def assist_draft(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/authoring/drafts/{draft_id}/assist"""
        return await self._call(
            "AssistDraft",
            "POST",
            "/v1/authoring/drafts/{draft_id}/assist",
            "application/json",
            request,
        )

    async def export_draft(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/authoring/drafts/{draft_id}/export"""
        return await self._call(
            "ExportDraft",
            "POST",
            "/v1/authoring/drafts/{draft_id}/export",
            "application/json",
            request,
        )

    async def validate_draft(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/authoring/drafts/{draft_id}/validate"""
        return await self._call(
            "ValidateDraft",
            "POST",
            "/v1/authoring/drafts/{draft_id}/validate",
            "application/json",
            request,
        )

    async def list_patterns(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/authoring/patterns"""
        return await self._call(
            "ListPatterns",
            "GET",
            "/v1/authoring/patterns",
            "application/json",
            request,
        )

    async def get_pattern(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/authoring/patterns/{id}"""
        return await self._call(
            "GetPattern",
            "GET",
            "/v1/authoring/patterns/{id}",
            "application/json",
            request,
        )

    async def budget_adjustments(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/budgets/{id}/adjustments"""
        return await self._call(
            "BudgetAdjustments",
            "GET",
            "/v1/budgets/{id}/adjustments",
            "application/json",
            request,
        )

    async def reconcile_budget(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/budgets/{id}/adjustments"""
        return await self._call(
            "ReconcileBudget",
            "POST",
            "/v1/budgets/{id}/adjustments",
            "application/json",
            request,
        )

    async def budget_evidence(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/budgets/{id}/evidence"""
        return await self._call(
            "BudgetEvidence",
            "GET",
            "/v1/budgets/{id}/evidence",
            "application/json",
            request,
        )

    async def apply_rules(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/chronology-rules"""
        return await self._call(
            "ApplyRules",
            "POST",
            "/v1/chronology-rules",
            "text/yaml",
            request,
        )

    async def get_rules(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/chronology-rules/{name}"""
        return await self._call(
            "GetRules",
            "GET",
            "/v1/chronology-rules/{name}",
            "application/json",
            request,
        )

    async def get_claim(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/claims/{claim_id}"""
        return await self._call(
            "GetClaim",
            "GET",
            "/v1/claims/{claim_id}",
            "application/json",
            request,
        )

    async def list_collections(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/collections"""
        return await self._call(
            "ListCollections",
            "GET",
            "/v1/collections",
            "application/json",
            request,
        )

    async def create_collection(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/collections"""
        return await self._call(
            "CreateCollection",
            "POST",
            "/v1/collections",
            "application/json",
            request,
        )

    async def activate_collection_index(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/collections/{collection_id}/activate-index"""
        return await self._call(
            "ActivateCollectionIndex",
            "POST",
            "/v1/collections/{collection_id}/activate-index",
            "application/json",
            request,
        )

    async def get_collection(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/collections/{id}"""
        return await self._call(
            "GetCollection",
            "GET",
            "/v1/collections/{id}",
            "application/json",
            request,
        )

    async def seal(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/evidence"""
        return await self._call(
            "Seal",
            "POST",
            "/v1/evidence",
            "application/json",
            request,
        )

    async def purge(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """DELETE /v1/evidence/{evidence_id}"""
        return await self._call(
            "Purge",
            "DELETE",
            "/v1/evidence/{evidence_id}",
            "application/json",
            request,
        )

    async def get_manifest(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/evidence/{evidence_id}"""
        return await self._call(
            "GetManifest",
            "GET",
            "/v1/evidence/{evidence_id}",
            "application/json",
            request,
        )

    async def get_accesses(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/evidence/{evidence_id}/accesses"""
        return await self._call(
            "GetAccesses",
            "GET",
            "/v1/evidence/{evidence_id}/accesses",
            "application/json",
            request,
        )

    async def put_bytes(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """PUT /v1/evidence/{evidence_id}/bytes"""
        return await self._call(
            "PutBytes",
            "PUT",
            "/v1/evidence/{evidence_id}/bytes",
            "application/octet-stream",
            request,
        )

    async def commit(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/evidence/{evidence_id}/commit"""
        return await self._call(
            "Commit",
            "POST",
            "/v1/evidence/{evidence_id}/commit",
            "application/json",
            request,
        )

    async def legal_hold(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/evidence/{evidence_id}/legal-hold"""
        return await self._call(
            "LegalHold",
            "POST",
            "/v1/evidence/{evidence_id}/legal-hold",
            "application/json",
            request,
        )

    async def get_rows(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/evidence/{evidence_id}/rows"""
        return await self._call(
            "GetRows",
            "GET",
            "/v1/evidence/{evidence_id}/rows",
            "application/json",
            request,
        )

    async def backfill(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/index-artifacts/backfill"""
        return await self._call(
            "Backfill",
            "POST",
            "/v1/index-artifacts/backfill",
            "application/json",
            request,
        )

    async def artifact_status(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/index-artifacts/{index_version_id}"""
        return await self._call(
            "ArtifactStatus",
            "GET",
            "/v1/index-artifacts/{index_version_id}",
            "application/json",
            request,
        )

    async def bind_artifact(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/index-artifacts/{index_version_id}/bind"""
        return await self._call(
            "BindArtifact",
            "POST",
            "/v1/index-artifacts/{index_version_id}/bind",
            "application/json",
            request,
        )

    async def promote_artifact(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/index-artifacts/{index_version_id}/promote"""
        return await self._call(
            "PromoteArtifact",
            "POST",
            "/v1/index-artifacts/{index_version_id}/promote",
            "application/json",
            request,
        )

    async def rebuild_artifact(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/index-artifacts/{index_version_id}/rebuild"""
        return await self._call(
            "RebuildArtifact",
            "POST",
            "/v1/index-artifacts/{index_version_id}/rebuild",
            "application/json",
            request,
        )

    async def verify_artifacts(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/index-artifacts/{index_version_id}/verify"""
        return await self._call(
            "VerifyArtifacts",
            "POST",
            "/v1/index-artifacts/{index_version_id}/verify",
            "application/json",
            request,
        )

    async def list_jobs(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/index-build-jobs"""
        return await self._call(
            "ListJobs",
            "GET",
            "/v1/index-build-jobs",
            "application/json",
            request,
        )

    async def enqueue_job(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/index-build-jobs"""
        return await self._call(
            "EnqueueJob",
            "POST",
            "/v1/index-build-jobs",
            "application/json",
            request,
        )

    async def get_job(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/index-build-jobs/{job_id}"""
        return await self._call(
            "GetJob",
            "GET",
            "/v1/index-build-jobs/{job_id}",
            "application/json",
            request,
        )

    async def cancel_job(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/index-build-jobs/{job_id}/cancel"""
        return await self._call(
            "CancelJob",
            "POST",
            "/v1/index-build-jobs/{job_id}/cancel",
            "application/json",
            request,
        )

    async def get_index(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/indexes/{shape_ref}"""
        return await self._call(
            "GetIndex",
            "GET",
            "/v1/indexes/{shape_ref}",
            "application/json",
            request,
        )

    async def build_index(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/indexes/{shape_ref}/build"""
        return await self._call(
            "BuildIndex",
            "POST",
            "/v1/indexes/{shape_ref}/build",
            "application/json",
            request,
        )

    async def ingest_file(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/ingest"""
        return await self._call(
            "IngestFile",
            "POST",
            "/v1/ingest",
            "application/json",
            request,
        )

    async def ingest_batch(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/ingest/batch"""
        return await self._call(
            "IngestBatch",
            "POST",
            "/v1/ingest/batch",
            "application/json",
            request,
        )

    async def bulk_open(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/ingest/bulk"""
        return await self._call(
            "BulkOpen",
            "POST",
            "/v1/ingest/bulk",
            "application/json",
            request,
        )

    async def bulk_status(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/ingest/bulk/{bulk_id}"""
        return await self._call(
            "BulkStatus",
            "GET",
            "/v1/ingest/bulk/{bulk_id}",
            "application/json",
            request,
        )

    async def bulk_chunk(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/ingest/bulk/{bulk_id}/chunk"""
        return await self._call(
            "BulkChunk",
            "POST",
            "/v1/ingest/bulk/{bulk_id}/chunk",
            "application/json",
            request,
        )

    async def bulk_complete(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/ingest/bulk/{bulk_id}/complete"""
        return await self._call(
            "BulkComplete",
            "POST",
            "/v1/ingest/bulk/{bulk_id}/complete",
            "application/json",
            request,
        )

    async def get_max_tokens(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/max-tokens"""
        return await self._call(
            "GetMaxTokens",
            "GET",
            "/v1/max-tokens",
            "application/json",
            request,
        )

    async def replace_max_tokens(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/max-tokens"""
        return await self._call(
            "ReplaceMaxTokens",
            "POST",
            "/v1/max-tokens",
            "application/json",
            request,
        )

    async def add_monetary_observation(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/monetary/observations"""
        return await self._call(
            "AddMonetaryObservation",
            "POST",
            "/v1/monetary/observations",
            "application/json",
            request,
        )

    async def monetary_prices(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/monetary/prices"""
        return await self._call(
            "MonetaryPrices",
            "GET",
            "/v1/monetary/prices",
            "application/json",
            request,
        )

    async def add_monetary_price(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/monetary/prices"""
        return await self._call(
            "AddMonetaryPrice",
            "POST",
            "/v1/monetary/prices",
            "application/json",
            request,
        )

    async def list_providers(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/providers"""
        return await self._call(
            "ListProviders",
            "GET",
            "/v1/providers",
            "application/json",
            request,
        )

    async def apply_provider(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/providers"""
        return await self._call(
            "ApplyProvider",
            "POST",
            "/v1/providers",
            "text/yaml",
            request,
        )

    async def provider_complete(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/providers/{name}/complete"""
        return await self._call(
            "ProviderComplete",
            "POST",
            "/v1/providers/{name}/complete",
            "application/json",
            request,
        )

    async def provider_embed(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/providers/{name}/embed"""
        return await self._call(
            "ProviderEmbed",
            "POST",
            "/v1/providers/{name}/embed",
            "application/json",
            request,
        )

    async def provider_health(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/providers/{name}/health"""
        return await self._call(
            "ProviderHealth",
            "GET",
            "/v1/providers/{name}/health",
            "application/json",
            request,
        )

    async def audit(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/audit"""
        return await self._call(
            "Audit",
            "GET",
            "/v1/reports/audit",
            "application/json",
            request,
        )

    async def budget_usage_report(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/budget-usage"""
        return await self._call(
            "BudgetUsageReport",
            "GET",
            "/v1/reports/budget-usage",
            "application/json",
            request,
        )

    async def budgets(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/budgets"""
        return await self._call(
            "Budgets",
            "GET",
            "/v1/reports/budgets",
            "application/json",
            request,
        )

    async def cost(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/cost"""
        return await self._call(
            "Cost",
            "GET",
            "/v1/reports/cost",
            "application/json",
            request,
        )

    async def endpoints(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/endpoints"""
        return await self._call(
            "Endpoints",
            "GET",
            "/v1/reports/endpoints",
            "application/json",
            request,
        )

    async def evidence_report(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/evidence"""
        return await self._call(
            "EvidenceReport",
            "GET",
            "/v1/reports/evidence",
            "application/json",
            request,
        )

    async def matrix_report(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/matrix"""
        return await self._call(
            "MatrixReport",
            "GET",
            "/v1/reports/matrix",
            "application/json",
            request,
        )

    async def monetary_report(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/money"""
        return await self._call(
            "MonetaryReport",
            "GET",
            "/v1/reports/money",
            "application/json",
            request,
        )

    async def runbook_report(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/runbooks"""
        return await self._call(
            "RunbookReport",
            "GET",
            "/v1/reports/runbooks",
            "application/json",
            request,
        )

    async def sessions_report(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/sessions"""
        return await self._call(
            "SessionsReport",
            "GET",
            "/v1/reports/sessions",
            "application/json",
            request,
        )

    async def timeseries(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/timeseries"""
        return await self._call(
            "Timeseries",
            "GET",
            "/v1/reports/timeseries",
            "application/json",
            request,
        )

    async def usage(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/reports/usage"""
        return await self._call(
            "Usage",
            "GET",
            "/v1/reports/usage",
            "application/json",
            request,
        )

    async def rollout_set(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """PUT /v1/retrieval-rollout"""
        return await self._call(
            "RolloutSet",
            "PUT",
            "/v1/retrieval-rollout",
            "application/json",
            request,
        )

    async def rollout_get(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/retrieval-rollout/{scope_kind}/{scope_id}"""
        return await self._call(
            "RolloutGet",
            "GET",
            "/v1/retrieval-rollout/{scope_kind}/{scope_id}",
            "application/json",
            request,
        )

    async def list_runbooks(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/runbooks"""
        return await self._call(
            "ListRunbooks",
            "GET",
            "/v1/runbooks",
            "application/json",
            request,
        )

    async def apply_runbook(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/runbooks"""
        return await self._call(
            "ApplyRunbook",
            "POST",
            "/v1/runbooks",
            "text/yaml",
            request,
        )

    async def validate_runbook(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/runbooks/validate"""
        return await self._call(
            "ValidateRunbook",
            "POST",
            "/v1/runbooks/validate",
            "text/yaml",
            request,
        )

    async def get_runbook_info(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/runbooks/{name}"""
        return await self._call(
            "GetRunbookInfo",
            "GET",
            "/v1/runbooks/{name}",
            "application/json",
            request,
        )

    async def remove_confirm(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/runbooks/{name}/remove-confirm"""
        return await self._call(
            "RemoveConfirm",
            "POST",
            "/v1/runbooks/{name}/remove-confirm",
            "application/json",
            request,
        )

    async def remove_request(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/runbooks/{name}/remove-request"""
        return await self._call(
            "RemoveRequest",
            "POST",
            "/v1/runbooks/{name}/remove-request",
            "application/json",
            request,
        )

    async def run_runbook(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/runbooks/{name}/runs"""
        return await self._call(
            "RunRunbook",
            "POST",
            "/v1/runbooks/{name}/runs",
            "application/json",
            request,
        )

    async def create_session(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/runbooks/{name}/sessions"""
        return await self._call(
            "CreateSession",
            "POST",
            "/v1/runbooks/{name}/sessions",
            "application/json",
            request,
        )

    async def get_run(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/runs/{run_id}"""
        return await self._call(
            "GetRun",
            "GET",
            "/v1/runs/{run_id}",
            "application/json",
            request,
        )

    async def approve_step(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/runs/{run_id}/steps/{ordinal}/approve"""
        return await self._call(
            "ApproveStep",
            "POST",
            "/v1/runs/{run_id}/steps/{ordinal}/approve",
            "application/json",
            request,
        )

    async def hybrid_search(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/search"""
        return await self._call(
            "HybridSearch",
            "POST",
            "/v1/search",
            "application/json",
            request,
        )

    async def get_session(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/sessions/{id}"""
        return await self._call(
            "GetSession",
            "GET",
            "/v1/sessions/{id}",
            "application/json",
            request,
        )

    async def close_session(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/sessions/{id}/close"""
        return await self._call(
            "CloseSession",
            "POST",
            "/v1/sessions/{id}/close",
            "application/json",
            request,
        )

    async def turn(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/sessions/{id}/turns"""
        return await self._call(
            "Turn",
            "POST",
            "/v1/sessions/{id}/turns",
            "application/json",
            request,
        )

    async def turn_stream(
        self,
        request: ApiRequest | None = None,
    ) -> AsyncIterator[ApiResponse]:
        """POST /v1/sessions/{id}/turns/stream"""
        async for part in self._stream(
            "TurnStream",
            "POST",
            "/v1/sessions/{id}/turns/stream",
            "application/json",
            request,
        ):
            yield part

    async def apply_shape(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/shapes"""
        return await self._call(
            "ApplyShape",
            "POST",
            "/v1/shapes",
            "text/yaml",
            request,
        )

    async def put_source(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """PUT /v1/sources"""
        return await self._call(
            "PutSource",
            "PUT",
            "/v1/sources",
            "application/octet-stream",
            request,
        )

    async def get_source(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/sources/{source_id}"""
        return await self._call(
            "GetSource",
            "GET",
            "/v1/sources/{source_id}",
            "application/json",
            request,
        )

    async def create_version(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/versions"""
        return await self._call(
            "CreateVersion",
            "POST",
            "/v1/versions",
            "application/json",
            request,
        )

    async def get_anchors(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/versions/{version_id}/anchors"""
        return await self._call(
            "GetAnchors",
            "GET",
            "/v1/versions/{version_id}/anchors",
            "application/json",
            request,
        )

    async def lock_anchor(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/versions/{version_id}/anchors"""
        return await self._call(
            "LockAnchor",
            "POST",
            "/v1/versions/{version_id}/anchors",
            "application/json",
            request,
        )

    async def propose_claim(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/versions/{version_id}/claims"""
        return await self._call(
            "ProposeClaim",
            "POST",
            "/v1/versions/{version_id}/claims",
            "application/json",
            request,
        )

    async def get_context(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/versions/{version_id}/context"""
        return await self._call(
            "GetContext",
            "GET",
            "/v1/versions/{version_id}/context",
            "application/json",
            request,
        )

    async def get_counters(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/versions/{version_id}/counters"""
        return await self._call(
            "GetCounters",
            "GET",
            "/v1/versions/{version_id}/counters",
            "application/json",
            request,
        )

    async def record_counts(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/versions/{version_id}/counters"""
        return await self._call(
            "RecordCounts",
            "POST",
            "/v1/versions/{version_id}/counters",
            "application/json",
            request,
        )

    async def get_digests(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/versions/{version_id}/digests"""
        return await self._call(
            "GetDigests",
            "GET",
            "/v1/versions/{version_id}/digests",
            "application/json",
            request,
        )

    async def upsert_digest(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """PUT /v1/versions/{version_id}/digests"""
        return await self._call(
            "UpsertDigest",
            "PUT",
            "/v1/versions/{version_id}/digests",
            "application/json",
            request,
        )

    async def append_events(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/versions/{version_id}/events"""
        return await self._call(
            "AppendEvents",
            "POST",
            "/v1/versions/{version_id}/events",
            "application/json",
            request,
        )

    async def get_facts(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/versions/{version_id}/facts"""
        return await self._call(
            "GetFacts",
            "GET",
            "/v1/versions/{version_id}/facts",
            "application/json",
            request,
        )

    async def get_findings(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/versions/{version_id}/findings"""
        return await self._call(
            "GetFindings",
            "GET",
            "/v1/versions/{version_id}/findings",
            "application/json",
            request,
        )

    async def record_findings(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/versions/{version_id}/findings"""
        return await self._call(
            "RecordFindings",
            "POST",
            "/v1/versions/{version_id}/findings",
            "application/json",
            request,
        )

    async def get_head(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/versions/{version_id}/head"""
        return await self._call(
            "GetHead",
            "GET",
            "/v1/versions/{version_id}/head",
            "application/json",
            request,
        )

    async def record_ingest(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/versions/{version_id}/ingests"""
        return await self._call(
            "RecordIngest",
            "POST",
            "/v1/versions/{version_id}/ingests",
            "application/json",
            request,
        )

    async def get_lineage(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/versions/{version_id}/lineage"""
        return await self._call(
            "GetLineage",
            "GET",
            "/v1/versions/{version_id}/lineage",
            "application/json",
            request,
        )

    async def get_promises(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /v1/versions/{version_id}/promises"""
        return await self._call(
            "GetPromises",
            "GET",
            "/v1/versions/{version_id}/promises",
            "application/json",
            request,
        )

    async def open_promise(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/versions/{version_id}/promises"""
        return await self._call(
            "OpenPromise",
            "POST",
            "/v1/versions/{version_id}/promises",
            "application/json",
            request,
        )

    async def fulfill_promise(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """POST /v1/versions/{version_id}/promises/{key}/fulfill"""
        return await self._call(
            "FulfillPromise",
            "POST",
            "/v1/versions/{version_id}/promises/{key}/fulfill",
            "application/json",
            request,
        )

    async def version_info(
        self,
        request: ApiRequest | None = None,
    ) -> ApiResponse:
        """GET /version"""
        return await self._call(
            "VersionInfo",
            "GET",
            "/version",
            "application/json",
            request,
        )
