// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate_server_api.py.
use super::*;
#[tonic::async_trait]
impl pb::server_api_service_server::ServerApiService for ServerApiSvc {
    async fn healthai(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/healthai", "application/json").await
    }
    async fn healthz(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/healthz", "application/json").await
    }
    async fn openapi_json(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/openapi.json", "application/json").await
    }
    async fn readyz(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/readyz", "application/json").await
    }
    async fn compose_answer(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1.2/answers", "application/json").await
    }
    async fn get_collection_governance(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1.2/collections/{id}/governance", "application/json").await
    }
    async fn replace_collection_governance(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "PUT", "/v1.2/collections/{id}/governance", "application/json").await
    }
    async fn authorize_publication(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1.2/collections/{id}/publications/{publication_id}", "application/json").await
    }
    async fn get_collection_vocabulary(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1.2/collections/{id}/vocabulary", "application/json").await
    }
    async fn update_collection_vocabulary(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "PATCH", "/v1.2/collections/{id}/vocabulary", "application/json").await
    }
    async fn replace_collection_vocabulary(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "PUT", "/v1.2/collections/{id}/vocabulary", "application/json").await
    }
    async fn refresh_collection_vocabulary(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1.2/collections/{id}/vocabulary/refresh", "application/json").await
    }
    async fn get_vocabulary_revision(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1.2/collections/{id}/vocabulary/revision", "application/json").await
    }
    async fn query_collections(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1.2/query", "application/json").await
    }
    async fn search_collection(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1.2/search", "application/json").await
    }
    async fn get_vocabulary_settings(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1.2/vocabulary-settings", "application/json").await
    }
    async fn replace_vocabulary_settings(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "PUT", "/v1.2/vocabulary-settings", "application/json").await
    }
    async fn list_tokens(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/access-tokens", "application/json").await
    }
    async fn issue_access_token(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/access-tokens", "application/json").await
    }
    async fn revoke_token(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/access-tokens/{jti}/revoke", "application/json").await
    }
    async fn list_drafts(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/authoring/drafts", "application/json").await
    }
    async fn create_draft(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/authoring/drafts", "application/json").await
    }
    async fn delete_draft(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "DELETE", "/v1/authoring/drafts/{draft_id}", "application/json").await
    }
    async fn get_draft(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/authoring/drafts/{draft_id}", "application/json").await
    }
    async fn update_answers(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "PUT", "/v1/authoring/drafts/{draft_id}/answers", "application/json").await
    }
    async fn apply_draft(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/authoring/drafts/{draft_id}/apply", "application/json").await
    }
    async fn assist_draft(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/authoring/drafts/{draft_id}/assist", "application/json").await
    }
    async fn export_draft(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/authoring/drafts/{draft_id}/export", "application/json").await
    }
    async fn validate_draft(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/authoring/drafts/{draft_id}/validate", "application/json").await
    }
    async fn list_patterns(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/authoring/patterns", "application/json").await
    }
    async fn get_pattern(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/authoring/patterns/{id}", "application/json").await
    }
    async fn apply_rules(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/chronology-rules", "text/yaml").await
    }
    async fn get_rules(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/chronology-rules/{name}", "application/json").await
    }
    async fn get_claim(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/claims/{claim_id}", "application/json").await
    }
    async fn list_collections(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/collections", "application/json").await
    }
    async fn create_collection(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/collections", "application/json").await
    }
    async fn activate_collection_index(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/collections/{collection_id}/activate-index", "application/json").await
    }
    async fn get_collection(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/collections/{id}", "application/json").await
    }
    async fn seal(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/evidence", "application/json").await
    }
    async fn purge(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "DELETE", "/v1/evidence/{evidence_id}", "application/json").await
    }
    async fn get_manifest(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/evidence/{evidence_id}", "application/json").await
    }
    async fn get_accesses(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/evidence/{evidence_id}/accesses", "application/json").await
    }
    async fn put_bytes(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "PUT", "/v1/evidence/{evidence_id}/bytes", "application/octet-stream").await
    }
    async fn commit(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/evidence/{evidence_id}/commit", "application/json").await
    }
    async fn legal_hold(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/evidence/{evidence_id}/legal-hold", "application/json").await
    }
    async fn get_rows(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/evidence/{evidence_id}/rows", "application/json").await
    }
    async fn backfill(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/index-artifacts/backfill", "application/json").await
    }
    async fn artifact_status(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/index-artifacts/{index_version_id}", "application/json").await
    }
    async fn bind_artifact(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/index-artifacts/{index_version_id}/bind", "application/json").await
    }
    async fn promote_artifact(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/index-artifacts/{index_version_id}/promote", "application/json").await
    }
    async fn rebuild_artifact(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/index-artifacts/{index_version_id}/rebuild", "application/json").await
    }
    async fn verify_artifacts(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/index-artifacts/{index_version_id}/verify", "application/json").await
    }
    async fn list_jobs(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/index-build-jobs", "application/json").await
    }
    async fn enqueue_job(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/index-build-jobs", "application/json").await
    }
    async fn get_job(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/index-build-jobs/{job_id}", "application/json").await
    }
    async fn cancel_job(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/index-build-jobs/{job_id}/cancel", "application/json").await
    }
    async fn get_index(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/indexes/{shape_ref}", "application/json").await
    }
    async fn build_index(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/indexes/{shape_ref}/build", "application/json").await
    }
    async fn ingest_file(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/ingest", "application/json").await
    }
    async fn ingest_batch(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/ingest/batch", "application/json").await
    }
    async fn bulk_open(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/ingest/bulk", "application/json").await
    }
    async fn bulk_status(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/ingest/bulk/{bulk_id}", "application/json").await
    }
    async fn bulk_chunk(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/ingest/bulk/{bulk_id}/chunk", "application/json").await
    }
    async fn bulk_complete(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/ingest/bulk/{bulk_id}/complete", "application/json").await
    }
    async fn get_max_tokens(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/max-tokens", "application/json").await
    }
    async fn replace_max_tokens(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/max-tokens", "application/json").await
    }
    async fn list_providers(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/providers", "application/json").await
    }
    async fn apply_provider(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/providers", "text/yaml").await
    }
    async fn provider_complete(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/providers/{name}/complete", "application/json").await
    }
    async fn provider_embed(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/providers/{name}/embed", "application/json").await
    }
    async fn provider_health(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/providers/{name}/health", "application/json").await
    }
    async fn audit(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/reports/audit", "application/json").await
    }
    async fn budgets(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/reports/budgets", "application/json").await
    }
    async fn cost(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/reports/cost", "application/json").await
    }
    async fn endpoints(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/reports/endpoints", "application/json").await
    }
    async fn evidence_report(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/reports/evidence", "application/json").await
    }
    async fn matrix_report(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/reports/matrix", "application/json").await
    }
    async fn runbook_report(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/reports/runbooks", "application/json").await
    }
    async fn sessions_report(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/reports/sessions", "application/json").await
    }
    async fn timeseries(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/reports/timeseries", "application/json").await
    }
    async fn usage(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/reports/usage", "application/json").await
    }
    async fn rollout_set(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "PUT", "/v1/retrieval-rollout", "application/json").await
    }
    async fn rollout_get(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/retrieval-rollout/{scope_kind}/{scope_id}", "application/json").await
    }
    async fn list_runbooks(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/runbooks", "application/json").await
    }
    async fn apply_runbook(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/runbooks", "text/yaml").await
    }
    async fn validate_runbook(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/runbooks/validate", "text/yaml").await
    }
    async fn get_runbook_info(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/runbooks/{name}", "application/json").await
    }
    async fn remove_confirm(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/runbooks/{name}/remove-confirm", "application/json").await
    }
    async fn remove_request(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/runbooks/{name}/remove-request", "application/json").await
    }
    async fn run_runbook(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/runbooks/{name}/runs", "application/json").await
    }
    async fn create_session(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/runbooks/{name}/sessions", "application/json").await
    }
    async fn get_run(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/runs/{run_id}", "application/json").await
    }
    async fn approve_step(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/runs/{run_id}/steps/{ordinal}/approve", "application/json").await
    }
    async fn hybrid_search(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/search", "application/json").await
    }
    async fn get_session(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/sessions/{id}", "application/json").await
    }
    async fn close_session(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/sessions/{id}/close", "application/json").await
    }
    async fn turn(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/sessions/{id}/turns", "application/json").await
    }
    type TurnStreamStream = ApiStream;
    async fn turn_stream(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<Self::TurnStreamStream>, Status> {
        self.stream(request, "POST", "/v1/sessions/{id}/turns/stream", "application/json").await
    }
    async fn apply_shape(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/shapes", "text/yaml").await
    }
    async fn put_source(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "PUT", "/v1/sources", "application/octet-stream").await
    }
    async fn get_source(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/sources/{source_id}", "application/json").await
    }
    async fn create_version(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/versions", "application/json").await
    }
    async fn get_anchors(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/versions/{version_id}/anchors", "application/json").await
    }
    async fn lock_anchor(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/versions/{version_id}/anchors", "application/json").await
    }
    async fn propose_claim(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/versions/{version_id}/claims", "application/json").await
    }
    async fn get_context(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/versions/{version_id}/context", "application/json").await
    }
    async fn get_counters(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/versions/{version_id}/counters", "application/json").await
    }
    async fn record_counts(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/versions/{version_id}/counters", "application/json").await
    }
    async fn get_digests(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/versions/{version_id}/digests", "application/json").await
    }
    async fn upsert_digest(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "PUT", "/v1/versions/{version_id}/digests", "application/json").await
    }
    async fn append_events(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/versions/{version_id}/events", "application/json").await
    }
    async fn get_facts(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/versions/{version_id}/facts", "application/json").await
    }
    async fn get_findings(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/versions/{version_id}/findings", "application/json").await
    }
    async fn record_findings(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/versions/{version_id}/findings", "application/json").await
    }
    async fn get_head(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/versions/{version_id}/head", "application/json").await
    }
    async fn record_ingest(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/versions/{version_id}/ingests", "application/json").await
    }
    async fn get_lineage(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/versions/{version_id}/lineage", "application/json").await
    }
    async fn get_promises(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/v1/versions/{version_id}/promises", "application/json").await
    }
    async fn open_promise(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/versions/{version_id}/promises", "application/json").await
    }
    async fn fulfill_promise(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "POST", "/v1/versions/{version_id}/promises/{key}/fulfill", "application/json").await
    }
    async fn version_info(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<pb::ServerApiResponse>, Status> {
        self.unary(request, "GET", "/version", "application/json").await
    }
}
