// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate_server_api.py.
package io.ioka.munarium.client;
import java.util.concurrent.CompletableFuture;
import java.util.function.Consumer;
public final class ServerApiClient extends ServerApiTransport {
    public ServerApiClient(MunariumClientOptions options, boolean grpc) { super(options, grpc); }
    /** GET /healthai */
    public ApiResponse healthai(ApiRequest request) { return call("Healthai", "GET", "/healthai", "application/json", request); }
    public CompletableFuture<ApiResponse> healthaiAsync(ApiRequest request) { return async(() -> healthai(request)); }
    /** GET /healthz */
    public ApiResponse healthz(ApiRequest request) { return call("Healthz", "GET", "/healthz", "application/json", request); }
    public CompletableFuture<ApiResponse> healthzAsync(ApiRequest request) { return async(() -> healthz(request)); }
    /** GET /openapi.json */
    public ApiResponse openapiJson(ApiRequest request) { return call("OpenapiJson", "GET", "/openapi.json", "application/json", request); }
    public CompletableFuture<ApiResponse> openapiJsonAsync(ApiRequest request) { return async(() -> openapiJson(request)); }
    /** GET /readyz */
    public ApiResponse readyz(ApiRequest request) { return call("Readyz", "GET", "/readyz", "application/json", request); }
    public CompletableFuture<ApiResponse> readyzAsync(ApiRequest request) { return async(() -> readyz(request)); }
    /** POST /v1.2/answers */
    public ApiResponse composeAnswer(ApiRequest request) { return call("ComposeAnswer", "POST", "/v1.2/answers", "application/json", request); }
    public CompletableFuture<ApiResponse> composeAnswerAsync(ApiRequest request) { return async(() -> composeAnswer(request)); }
    /** GET /v1.2/collections/{id}/governance */
    public ApiResponse getCollectionGovernance(ApiRequest request) { return call("GetCollectionGovernance", "GET", "/v1.2/collections/{id}/governance", "application/json", request); }
    public CompletableFuture<ApiResponse> getCollectionGovernanceAsync(ApiRequest request) { return async(() -> getCollectionGovernance(request)); }
    /** PUT /v1.2/collections/{id}/governance */
    public ApiResponse replaceCollectionGovernance(ApiRequest request) { return call("ReplaceCollectionGovernance", "PUT", "/v1.2/collections/{id}/governance", "application/json", request); }
    public CompletableFuture<ApiResponse> replaceCollectionGovernanceAsync(ApiRequest request) { return async(() -> replaceCollectionGovernance(request)); }
    /** GET /v1.2/collections/{id}/publications/{publication_id} */
    public ApiResponse authorizePublication(ApiRequest request) { return call("AuthorizePublication", "GET", "/v1.2/collections/{id}/publications/{publication_id}", "application/json", request); }
    public CompletableFuture<ApiResponse> authorizePublicationAsync(ApiRequest request) { return async(() -> authorizePublication(request)); }
    /** GET /v1.2/collections/{id}/vocabulary */
    public ApiResponse getCollectionVocabulary(ApiRequest request) { return call("GetCollectionVocabulary", "GET", "/v1.2/collections/{id}/vocabulary", "application/json", request); }
    public CompletableFuture<ApiResponse> getCollectionVocabularyAsync(ApiRequest request) { return async(() -> getCollectionVocabulary(request)); }
    /** PATCH /v1.2/collections/{id}/vocabulary */
    public ApiResponse updateCollectionVocabulary(ApiRequest request) { return call("UpdateCollectionVocabulary", "PATCH", "/v1.2/collections/{id}/vocabulary", "application/json", request); }
    public CompletableFuture<ApiResponse> updateCollectionVocabularyAsync(ApiRequest request) { return async(() -> updateCollectionVocabulary(request)); }
    /** PUT /v1.2/collections/{id}/vocabulary */
    public ApiResponse replaceCollectionVocabulary(ApiRequest request) { return call("ReplaceCollectionVocabulary", "PUT", "/v1.2/collections/{id}/vocabulary", "application/json", request); }
    public CompletableFuture<ApiResponse> replaceCollectionVocabularyAsync(ApiRequest request) { return async(() -> replaceCollectionVocabulary(request)); }
    /** POST /v1.2/collections/{id}/vocabulary/refresh */
    public ApiResponse refreshCollectionVocabulary(ApiRequest request) { return call("RefreshCollectionVocabulary", "POST", "/v1.2/collections/{id}/vocabulary/refresh", "application/json", request); }
    public CompletableFuture<ApiResponse> refreshCollectionVocabularyAsync(ApiRequest request) { return async(() -> refreshCollectionVocabulary(request)); }
    /** GET /v1.2/collections/{id}/vocabulary/revision */
    public ApiResponse getVocabularyRevision(ApiRequest request) { return call("GetVocabularyRevision", "GET", "/v1.2/collections/{id}/vocabulary/revision", "application/json", request); }
    public CompletableFuture<ApiResponse> getVocabularyRevisionAsync(ApiRequest request) { return async(() -> getVocabularyRevision(request)); }
    /** POST /v1.2/query */
    public ApiResponse queryCollections(ApiRequest request) { return call("QueryCollections", "POST", "/v1.2/query", "application/json", request); }
    public CompletableFuture<ApiResponse> queryCollectionsAsync(ApiRequest request) { return async(() -> queryCollections(request)); }
    /** POST /v1.2/search */
    public ApiResponse searchCollection(ApiRequest request) { return call("SearchCollection", "POST", "/v1.2/search", "application/json", request); }
    public CompletableFuture<ApiResponse> searchCollectionAsync(ApiRequest request) { return async(() -> searchCollection(request)); }
    /** GET /v1.2/vocabulary-settings */
    public ApiResponse getVocabularySettings(ApiRequest request) { return call("GetVocabularySettings", "GET", "/v1.2/vocabulary-settings", "application/json", request); }
    public CompletableFuture<ApiResponse> getVocabularySettingsAsync(ApiRequest request) { return async(() -> getVocabularySettings(request)); }
    /** PUT /v1.2/vocabulary-settings */
    public ApiResponse replaceVocabularySettings(ApiRequest request) { return call("ReplaceVocabularySettings", "PUT", "/v1.2/vocabulary-settings", "application/json", request); }
    public CompletableFuture<ApiResponse> replaceVocabularySettingsAsync(ApiRequest request) { return async(() -> replaceVocabularySettings(request)); }
    /** GET /v1/access-tokens */
    public ApiResponse listTokens(ApiRequest request) { return call("ListTokens", "GET", "/v1/access-tokens", "application/json", request); }
    public CompletableFuture<ApiResponse> listTokensAsync(ApiRequest request) { return async(() -> listTokens(request)); }
    /** POST /v1/access-tokens */
    public ApiResponse issueAccessToken(ApiRequest request) { return call("IssueAccessToken", "POST", "/v1/access-tokens", "application/json", request); }
    public CompletableFuture<ApiResponse> issueAccessTokenAsync(ApiRequest request) { return async(() -> issueAccessToken(request)); }
    /** POST /v1/access-tokens/{jti}/revoke */
    public ApiResponse revokeToken(ApiRequest request) { return call("RevokeToken", "POST", "/v1/access-tokens/{jti}/revoke", "application/json", request); }
    public CompletableFuture<ApiResponse> revokeTokenAsync(ApiRequest request) { return async(() -> revokeToken(request)); }
    /** GET /v1/authoring/drafts */
    public ApiResponse listDrafts(ApiRequest request) { return call("ListDrafts", "GET", "/v1/authoring/drafts", "application/json", request); }
    public CompletableFuture<ApiResponse> listDraftsAsync(ApiRequest request) { return async(() -> listDrafts(request)); }
    /** POST /v1/authoring/drafts */
    public ApiResponse createDraft(ApiRequest request) { return call("CreateDraft", "POST", "/v1/authoring/drafts", "application/json", request); }
    public CompletableFuture<ApiResponse> createDraftAsync(ApiRequest request) { return async(() -> createDraft(request)); }
    /** DELETE /v1/authoring/drafts/{draft_id} */
    public ApiResponse deleteDraft(ApiRequest request) { return call("DeleteDraft", "DELETE", "/v1/authoring/drafts/{draft_id}", "application/json", request); }
    public CompletableFuture<ApiResponse> deleteDraftAsync(ApiRequest request) { return async(() -> deleteDraft(request)); }
    /** GET /v1/authoring/drafts/{draft_id} */
    public ApiResponse getDraft(ApiRequest request) { return call("GetDraft", "GET", "/v1/authoring/drafts/{draft_id}", "application/json", request); }
    public CompletableFuture<ApiResponse> getDraftAsync(ApiRequest request) { return async(() -> getDraft(request)); }
    /** PUT /v1/authoring/drafts/{draft_id}/answers */
    public ApiResponse updateAnswers(ApiRequest request) { return call("UpdateAnswers", "PUT", "/v1/authoring/drafts/{draft_id}/answers", "application/json", request); }
    public CompletableFuture<ApiResponse> updateAnswersAsync(ApiRequest request) { return async(() -> updateAnswers(request)); }
    /** POST /v1/authoring/drafts/{draft_id}/apply */
    public ApiResponse applyDraft(ApiRequest request) { return call("ApplyDraft", "POST", "/v1/authoring/drafts/{draft_id}/apply", "application/json", request); }
    public CompletableFuture<ApiResponse> applyDraftAsync(ApiRequest request) { return async(() -> applyDraft(request)); }
    /** POST /v1/authoring/drafts/{draft_id}/assist */
    public ApiResponse assistDraft(ApiRequest request) { return call("AssistDraft", "POST", "/v1/authoring/drafts/{draft_id}/assist", "application/json", request); }
    public CompletableFuture<ApiResponse> assistDraftAsync(ApiRequest request) { return async(() -> assistDraft(request)); }
    /** POST /v1/authoring/drafts/{draft_id}/export */
    public ApiResponse exportDraft(ApiRequest request) { return call("ExportDraft", "POST", "/v1/authoring/drafts/{draft_id}/export", "application/json", request); }
    public CompletableFuture<ApiResponse> exportDraftAsync(ApiRequest request) { return async(() -> exportDraft(request)); }
    /** POST /v1/authoring/drafts/{draft_id}/validate */
    public ApiResponse validateDraft(ApiRequest request) { return call("ValidateDraft", "POST", "/v1/authoring/drafts/{draft_id}/validate", "application/json", request); }
    public CompletableFuture<ApiResponse> validateDraftAsync(ApiRequest request) { return async(() -> validateDraft(request)); }
    /** GET /v1/authoring/patterns */
    public ApiResponse listPatterns(ApiRequest request) { return call("ListPatterns", "GET", "/v1/authoring/patterns", "application/json", request); }
    public CompletableFuture<ApiResponse> listPatternsAsync(ApiRequest request) { return async(() -> listPatterns(request)); }
    /** GET /v1/authoring/patterns/{id} */
    public ApiResponse getPattern(ApiRequest request) { return call("GetPattern", "GET", "/v1/authoring/patterns/{id}", "application/json", request); }
    public CompletableFuture<ApiResponse> getPatternAsync(ApiRequest request) { return async(() -> getPattern(request)); }
    /** GET /v1/budgets/{id}/adjustments */
    public ApiResponse budgetAdjustments(ApiRequest request) { return call("BudgetAdjustments", "GET", "/v1/budgets/{id}/adjustments", "application/json", request); }
    public CompletableFuture<ApiResponse> budgetAdjustmentsAsync(ApiRequest request) { return async(() -> budgetAdjustments(request)); }
    /** POST /v1/budgets/{id}/adjustments */
    public ApiResponse reconcileBudget(ApiRequest request) { return call("ReconcileBudget", "POST", "/v1/budgets/{id}/adjustments", "application/json", request); }
    public CompletableFuture<ApiResponse> reconcileBudgetAsync(ApiRequest request) { return async(() -> reconcileBudget(request)); }
    /** GET /v1/budgets/{id}/evidence */
    public ApiResponse budgetEvidence(ApiRequest request) { return call("BudgetEvidence", "GET", "/v1/budgets/{id}/evidence", "application/json", request); }
    public CompletableFuture<ApiResponse> budgetEvidenceAsync(ApiRequest request) { return async(() -> budgetEvidence(request)); }
    /** POST /v1/chronology-rules */
    public ApiResponse applyRules(ApiRequest request) { return call("ApplyRules", "POST", "/v1/chronology-rules", "text/yaml", request); }
    public CompletableFuture<ApiResponse> applyRulesAsync(ApiRequest request) { return async(() -> applyRules(request)); }
    /** GET /v1/chronology-rules/{name} */
    public ApiResponse getRules(ApiRequest request) { return call("GetRules", "GET", "/v1/chronology-rules/{name}", "application/json", request); }
    public CompletableFuture<ApiResponse> getRulesAsync(ApiRequest request) { return async(() -> getRules(request)); }
    /** GET /v1/claims/{claim_id} */
    public ApiResponse getClaim(ApiRequest request) { return call("GetClaim", "GET", "/v1/claims/{claim_id}", "application/json", request); }
    public CompletableFuture<ApiResponse> getClaimAsync(ApiRequest request) { return async(() -> getClaim(request)); }
    /** GET /v1/collections */
    public ApiResponse listCollections(ApiRequest request) { return call("ListCollections", "GET", "/v1/collections", "application/json", request); }
    public CompletableFuture<ApiResponse> listCollectionsAsync(ApiRequest request) { return async(() -> listCollections(request)); }
    /** POST /v1/collections */
    public ApiResponse createCollection(ApiRequest request) { return call("CreateCollection", "POST", "/v1/collections", "application/json", request); }
    public CompletableFuture<ApiResponse> createCollectionAsync(ApiRequest request) { return async(() -> createCollection(request)); }
    /** POST /v1/collections/{collection_id}/activate-index */
    public ApiResponse activateCollectionIndex(ApiRequest request) { return call("ActivateCollectionIndex", "POST", "/v1/collections/{collection_id}/activate-index", "application/json", request); }
    public CompletableFuture<ApiResponse> activateCollectionIndexAsync(ApiRequest request) { return async(() -> activateCollectionIndex(request)); }
    /** GET /v1/collections/{id} */
    public ApiResponse getCollection(ApiRequest request) { return call("GetCollection", "GET", "/v1/collections/{id}", "application/json", request); }
    public CompletableFuture<ApiResponse> getCollectionAsync(ApiRequest request) { return async(() -> getCollection(request)); }
    /** POST /v1/evidence */
    public ApiResponse seal(ApiRequest request) { return call("Seal", "POST", "/v1/evidence", "application/json", request); }
    public CompletableFuture<ApiResponse> sealAsync(ApiRequest request) { return async(() -> seal(request)); }
    /** DELETE /v1/evidence/{evidence_id} */
    public ApiResponse purge(ApiRequest request) { return call("Purge", "DELETE", "/v1/evidence/{evidence_id}", "application/json", request); }
    public CompletableFuture<ApiResponse> purgeAsync(ApiRequest request) { return async(() -> purge(request)); }
    /** GET /v1/evidence/{evidence_id} */
    public ApiResponse getManifest(ApiRequest request) { return call("GetManifest", "GET", "/v1/evidence/{evidence_id}", "application/json", request); }
    public CompletableFuture<ApiResponse> getManifestAsync(ApiRequest request) { return async(() -> getManifest(request)); }
    /** GET /v1/evidence/{evidence_id}/accesses */
    public ApiResponse getAccesses(ApiRequest request) { return call("GetAccesses", "GET", "/v1/evidence/{evidence_id}/accesses", "application/json", request); }
    public CompletableFuture<ApiResponse> getAccessesAsync(ApiRequest request) { return async(() -> getAccesses(request)); }
    /** PUT /v1/evidence/{evidence_id}/bytes */
    public ApiResponse putBytes(ApiRequest request) { return call("PutBytes", "PUT", "/v1/evidence/{evidence_id}/bytes", "application/octet-stream", request); }
    public CompletableFuture<ApiResponse> putBytesAsync(ApiRequest request) { return async(() -> putBytes(request)); }
    /** POST /v1/evidence/{evidence_id}/commit */
    public ApiResponse commit(ApiRequest request) { return call("Commit", "POST", "/v1/evidence/{evidence_id}/commit", "application/json", request); }
    public CompletableFuture<ApiResponse> commitAsync(ApiRequest request) { return async(() -> commit(request)); }
    /** POST /v1/evidence/{evidence_id}/legal-hold */
    public ApiResponse legalHold(ApiRequest request) { return call("LegalHold", "POST", "/v1/evidence/{evidence_id}/legal-hold", "application/json", request); }
    public CompletableFuture<ApiResponse> legalHoldAsync(ApiRequest request) { return async(() -> legalHold(request)); }
    /** GET /v1/evidence/{evidence_id}/rows */
    public ApiResponse getRows(ApiRequest request) { return call("GetRows", "GET", "/v1/evidence/{evidence_id}/rows", "application/json", request); }
    public CompletableFuture<ApiResponse> getRowsAsync(ApiRequest request) { return async(() -> getRows(request)); }
    /** POST /v1/index-artifacts/backfill */
    public ApiResponse backfill(ApiRequest request) { return call("Backfill", "POST", "/v1/index-artifacts/backfill", "application/json", request); }
    public CompletableFuture<ApiResponse> backfillAsync(ApiRequest request) { return async(() -> backfill(request)); }
    /** GET /v1/index-artifacts/{index_version_id} */
    public ApiResponse artifactStatus(ApiRequest request) { return call("ArtifactStatus", "GET", "/v1/index-artifacts/{index_version_id}", "application/json", request); }
    public CompletableFuture<ApiResponse> artifactStatusAsync(ApiRequest request) { return async(() -> artifactStatus(request)); }
    /** POST /v1/index-artifacts/{index_version_id}/bind */
    public ApiResponse bindArtifact(ApiRequest request) { return call("BindArtifact", "POST", "/v1/index-artifacts/{index_version_id}/bind", "application/json", request); }
    public CompletableFuture<ApiResponse> bindArtifactAsync(ApiRequest request) { return async(() -> bindArtifact(request)); }
    /** POST /v1/index-artifacts/{index_version_id}/promote */
    public ApiResponse promoteArtifact(ApiRequest request) { return call("PromoteArtifact", "POST", "/v1/index-artifacts/{index_version_id}/promote", "application/json", request); }
    public CompletableFuture<ApiResponse> promoteArtifactAsync(ApiRequest request) { return async(() -> promoteArtifact(request)); }
    /** POST /v1/index-artifacts/{index_version_id}/rebuild */
    public ApiResponse rebuildArtifact(ApiRequest request) { return call("RebuildArtifact", "POST", "/v1/index-artifacts/{index_version_id}/rebuild", "application/json", request); }
    public CompletableFuture<ApiResponse> rebuildArtifactAsync(ApiRequest request) { return async(() -> rebuildArtifact(request)); }
    /** POST /v1/index-artifacts/{index_version_id}/verify */
    public ApiResponse verifyArtifacts(ApiRequest request) { return call("VerifyArtifacts", "POST", "/v1/index-artifacts/{index_version_id}/verify", "application/json", request); }
    public CompletableFuture<ApiResponse> verifyArtifactsAsync(ApiRequest request) { return async(() -> verifyArtifacts(request)); }
    /** GET /v1/index-build-jobs */
    public ApiResponse listJobs(ApiRequest request) { return call("ListJobs", "GET", "/v1/index-build-jobs", "application/json", request); }
    public CompletableFuture<ApiResponse> listJobsAsync(ApiRequest request) { return async(() -> listJobs(request)); }
    /** POST /v1/index-build-jobs */
    public ApiResponse enqueueJob(ApiRequest request) { return call("EnqueueJob", "POST", "/v1/index-build-jobs", "application/json", request); }
    public CompletableFuture<ApiResponse> enqueueJobAsync(ApiRequest request) { return async(() -> enqueueJob(request)); }
    /** GET /v1/index-build-jobs/{job_id} */
    public ApiResponse getJob(ApiRequest request) { return call("GetJob", "GET", "/v1/index-build-jobs/{job_id}", "application/json", request); }
    public CompletableFuture<ApiResponse> getJobAsync(ApiRequest request) { return async(() -> getJob(request)); }
    /** POST /v1/index-build-jobs/{job_id}/cancel */
    public ApiResponse cancelJob(ApiRequest request) { return call("CancelJob", "POST", "/v1/index-build-jobs/{job_id}/cancel", "application/json", request); }
    public CompletableFuture<ApiResponse> cancelJobAsync(ApiRequest request) { return async(() -> cancelJob(request)); }
    /** GET /v1/indexes/{shape_ref} */
    public ApiResponse getIndex(ApiRequest request) { return call("GetIndex", "GET", "/v1/indexes/{shape_ref}", "application/json", request); }
    public CompletableFuture<ApiResponse> getIndexAsync(ApiRequest request) { return async(() -> getIndex(request)); }
    /** POST /v1/indexes/{shape_ref}/build */
    public ApiResponse buildIndex(ApiRequest request) { return call("BuildIndex", "POST", "/v1/indexes/{shape_ref}/build", "application/json", request); }
    public CompletableFuture<ApiResponse> buildIndexAsync(ApiRequest request) { return async(() -> buildIndex(request)); }
    /** POST /v1/ingest */
    public ApiResponse ingestFile(ApiRequest request) { return call("IngestFile", "POST", "/v1/ingest", "application/json", request); }
    public CompletableFuture<ApiResponse> ingestFileAsync(ApiRequest request) { return async(() -> ingestFile(request)); }
    /** POST /v1/ingest/batch */
    public ApiResponse ingestBatch(ApiRequest request) { return call("IngestBatch", "POST", "/v1/ingest/batch", "application/json", request); }
    public CompletableFuture<ApiResponse> ingestBatchAsync(ApiRequest request) { return async(() -> ingestBatch(request)); }
    /** POST /v1/ingest/bulk */
    public ApiResponse bulkOpen(ApiRequest request) { return call("BulkOpen", "POST", "/v1/ingest/bulk", "application/json", request); }
    public CompletableFuture<ApiResponse> bulkOpenAsync(ApiRequest request) { return async(() -> bulkOpen(request)); }
    /** GET /v1/ingest/bulk/{bulk_id} */
    public ApiResponse bulkStatus(ApiRequest request) { return call("BulkStatus", "GET", "/v1/ingest/bulk/{bulk_id}", "application/json", request); }
    public CompletableFuture<ApiResponse> bulkStatusAsync(ApiRequest request) { return async(() -> bulkStatus(request)); }
    /** POST /v1/ingest/bulk/{bulk_id}/chunk */
    public ApiResponse bulkChunk(ApiRequest request) { return call("BulkChunk", "POST", "/v1/ingest/bulk/{bulk_id}/chunk", "application/json", request); }
    public CompletableFuture<ApiResponse> bulkChunkAsync(ApiRequest request) { return async(() -> bulkChunk(request)); }
    /** POST /v1/ingest/bulk/{bulk_id}/complete */
    public ApiResponse bulkComplete(ApiRequest request) { return call("BulkComplete", "POST", "/v1/ingest/bulk/{bulk_id}/complete", "application/json", request); }
    public CompletableFuture<ApiResponse> bulkCompleteAsync(ApiRequest request) { return async(() -> bulkComplete(request)); }
    /** GET /v1/max-tokens */
    public ApiResponse getMaxTokens(ApiRequest request) { return call("GetMaxTokens", "GET", "/v1/max-tokens", "application/json", request); }
    public CompletableFuture<ApiResponse> getMaxTokensAsync(ApiRequest request) { return async(() -> getMaxTokens(request)); }
    /** POST /v1/max-tokens */
    public ApiResponse replaceMaxTokens(ApiRequest request) { return call("ReplaceMaxTokens", "POST", "/v1/max-tokens", "application/json", request); }
    public CompletableFuture<ApiResponse> replaceMaxTokensAsync(ApiRequest request) { return async(() -> replaceMaxTokens(request)); }
    /** POST /v1/monetary/observations */
    public ApiResponse addMonetaryObservation(ApiRequest request) { return call("AddMonetaryObservation", "POST", "/v1/monetary/observations", "application/json", request); }
    public CompletableFuture<ApiResponse> addMonetaryObservationAsync(ApiRequest request) { return async(() -> addMonetaryObservation(request)); }
    /** GET /v1/monetary/prices */
    public ApiResponse monetaryPrices(ApiRequest request) { return call("MonetaryPrices", "GET", "/v1/monetary/prices", "application/json", request); }
    public CompletableFuture<ApiResponse> monetaryPricesAsync(ApiRequest request) { return async(() -> monetaryPrices(request)); }
    /** POST /v1/monetary/prices */
    public ApiResponse addMonetaryPrice(ApiRequest request) { return call("AddMonetaryPrice", "POST", "/v1/monetary/prices", "application/json", request); }
    public CompletableFuture<ApiResponse> addMonetaryPriceAsync(ApiRequest request) { return async(() -> addMonetaryPrice(request)); }
    /** GET /v1/providers */
    public ApiResponse listProviders(ApiRequest request) { return call("ListProviders", "GET", "/v1/providers", "application/json", request); }
    public CompletableFuture<ApiResponse> listProvidersAsync(ApiRequest request) { return async(() -> listProviders(request)); }
    /** POST /v1/providers */
    public ApiResponse applyProvider(ApiRequest request) { return call("ApplyProvider", "POST", "/v1/providers", "text/yaml", request); }
    public CompletableFuture<ApiResponse> applyProviderAsync(ApiRequest request) { return async(() -> applyProvider(request)); }
    /** POST /v1/providers/{name}/complete */
    public ApiResponse providerComplete(ApiRequest request) { return call("ProviderComplete", "POST", "/v1/providers/{name}/complete", "application/json", request); }
    public CompletableFuture<ApiResponse> providerCompleteAsync(ApiRequest request) { return async(() -> providerComplete(request)); }
    /** POST /v1/providers/{name}/embed */
    public ApiResponse providerEmbed(ApiRequest request) { return call("ProviderEmbed", "POST", "/v1/providers/{name}/embed", "application/json", request); }
    public CompletableFuture<ApiResponse> providerEmbedAsync(ApiRequest request) { return async(() -> providerEmbed(request)); }
    /** GET /v1/providers/{name}/health */
    public ApiResponse providerHealth(ApiRequest request) { return call("ProviderHealth", "GET", "/v1/providers/{name}/health", "application/json", request); }
    public CompletableFuture<ApiResponse> providerHealthAsync(ApiRequest request) { return async(() -> providerHealth(request)); }
    /** GET /v1/reports/audit */
    public ApiResponse audit(ApiRequest request) { return call("Audit", "GET", "/v1/reports/audit", "application/json", request); }
    public CompletableFuture<ApiResponse> auditAsync(ApiRequest request) { return async(() -> audit(request)); }
    /** GET /v1/reports/budget-usage */
    public ApiResponse budgetUsageReport(ApiRequest request) { return call("BudgetUsageReport", "GET", "/v1/reports/budget-usage", "application/json", request); }
    public CompletableFuture<ApiResponse> budgetUsageReportAsync(ApiRequest request) { return async(() -> budgetUsageReport(request)); }
    /** GET /v1/reports/budgets */
    public ApiResponse budgets(ApiRequest request) { return call("Budgets", "GET", "/v1/reports/budgets", "application/json", request); }
    public CompletableFuture<ApiResponse> budgetsAsync(ApiRequest request) { return async(() -> budgets(request)); }
    /** GET /v1/reports/cost */
    public ApiResponse cost(ApiRequest request) { return call("Cost", "GET", "/v1/reports/cost", "application/json", request); }
    public CompletableFuture<ApiResponse> costAsync(ApiRequest request) { return async(() -> cost(request)); }
    /** GET /v1/reports/endpoints */
    public ApiResponse endpoints(ApiRequest request) { return call("Endpoints", "GET", "/v1/reports/endpoints", "application/json", request); }
    public CompletableFuture<ApiResponse> endpointsAsync(ApiRequest request) { return async(() -> endpoints(request)); }
    /** GET /v1/reports/evidence */
    public ApiResponse evidenceReport(ApiRequest request) { return call("EvidenceReport", "GET", "/v1/reports/evidence", "application/json", request); }
    public CompletableFuture<ApiResponse> evidenceReportAsync(ApiRequest request) { return async(() -> evidenceReport(request)); }
    /** GET /v1/reports/matrix */
    public ApiResponse matrixReport(ApiRequest request) { return call("MatrixReport", "GET", "/v1/reports/matrix", "application/json", request); }
    public CompletableFuture<ApiResponse> matrixReportAsync(ApiRequest request) { return async(() -> matrixReport(request)); }
    /** GET /v1/reports/money */
    public ApiResponse monetaryReport(ApiRequest request) { return call("MonetaryReport", "GET", "/v1/reports/money", "application/json", request); }
    public CompletableFuture<ApiResponse> monetaryReportAsync(ApiRequest request) { return async(() -> monetaryReport(request)); }
    /** GET /v1/reports/runbooks */
    public ApiResponse runbookReport(ApiRequest request) { return call("RunbookReport", "GET", "/v1/reports/runbooks", "application/json", request); }
    public CompletableFuture<ApiResponse> runbookReportAsync(ApiRequest request) { return async(() -> runbookReport(request)); }
    /** GET /v1/reports/sessions */
    public ApiResponse sessionsReport(ApiRequest request) { return call("SessionsReport", "GET", "/v1/reports/sessions", "application/json", request); }
    public CompletableFuture<ApiResponse> sessionsReportAsync(ApiRequest request) { return async(() -> sessionsReport(request)); }
    /** GET /v1/reports/timeseries */
    public ApiResponse timeseries(ApiRequest request) { return call("Timeseries", "GET", "/v1/reports/timeseries", "application/json", request); }
    public CompletableFuture<ApiResponse> timeseriesAsync(ApiRequest request) { return async(() -> timeseries(request)); }
    /** GET /v1/reports/usage */
    public ApiResponse usage(ApiRequest request) { return call("Usage", "GET", "/v1/reports/usage", "application/json", request); }
    public CompletableFuture<ApiResponse> usageAsync(ApiRequest request) { return async(() -> usage(request)); }
    /** PUT /v1/retrieval-rollout */
    public ApiResponse rolloutSet(ApiRequest request) { return call("RolloutSet", "PUT", "/v1/retrieval-rollout", "application/json", request); }
    public CompletableFuture<ApiResponse> rolloutSetAsync(ApiRequest request) { return async(() -> rolloutSet(request)); }
    /** GET /v1/retrieval-rollout/{scope_kind}/{scope_id} */
    public ApiResponse rolloutGet(ApiRequest request) { return call("RolloutGet", "GET", "/v1/retrieval-rollout/{scope_kind}/{scope_id}", "application/json", request); }
    public CompletableFuture<ApiResponse> rolloutGetAsync(ApiRequest request) { return async(() -> rolloutGet(request)); }
    /** GET /v1/runbooks */
    public ApiResponse listRunbooks(ApiRequest request) { return call("ListRunbooks", "GET", "/v1/runbooks", "application/json", request); }
    public CompletableFuture<ApiResponse> listRunbooksAsync(ApiRequest request) { return async(() -> listRunbooks(request)); }
    /** POST /v1/runbooks */
    public ApiResponse applyRunbook(ApiRequest request) { return call("ApplyRunbook", "POST", "/v1/runbooks", "text/yaml", request); }
    public CompletableFuture<ApiResponse> applyRunbookAsync(ApiRequest request) { return async(() -> applyRunbook(request)); }
    /** POST /v1/runbooks/validate */
    public ApiResponse validateRunbook(ApiRequest request) { return call("ValidateRunbook", "POST", "/v1/runbooks/validate", "text/yaml", request); }
    public CompletableFuture<ApiResponse> validateRunbookAsync(ApiRequest request) { return async(() -> validateRunbook(request)); }
    /** GET /v1/runbooks/{name} */
    public ApiResponse getRunbookInfo(ApiRequest request) { return call("GetRunbookInfo", "GET", "/v1/runbooks/{name}", "application/json", request); }
    public CompletableFuture<ApiResponse> getRunbookInfoAsync(ApiRequest request) { return async(() -> getRunbookInfo(request)); }
    /** POST /v1/runbooks/{name}/remove-confirm */
    public ApiResponse removeConfirm(ApiRequest request) { return call("RemoveConfirm", "POST", "/v1/runbooks/{name}/remove-confirm", "application/json", request); }
    public CompletableFuture<ApiResponse> removeConfirmAsync(ApiRequest request) { return async(() -> removeConfirm(request)); }
    /** POST /v1/runbooks/{name}/remove-request */
    public ApiResponse removeRequest(ApiRequest request) { return call("RemoveRequest", "POST", "/v1/runbooks/{name}/remove-request", "application/json", request); }
    public CompletableFuture<ApiResponse> removeRequestAsync(ApiRequest request) { return async(() -> removeRequest(request)); }
    /** POST /v1/runbooks/{name}/runs */
    public ApiResponse runRunbook(ApiRequest request) { return call("RunRunbook", "POST", "/v1/runbooks/{name}/runs", "application/json", request); }
    public CompletableFuture<ApiResponse> runRunbookAsync(ApiRequest request) { return async(() -> runRunbook(request)); }
    /** POST /v1/runbooks/{name}/sessions */
    public ApiResponse createSession(ApiRequest request) { return call("CreateSession", "POST", "/v1/runbooks/{name}/sessions", "application/json", request); }
    public CompletableFuture<ApiResponse> createSessionAsync(ApiRequest request) { return async(() -> createSession(request)); }
    /** GET /v1/runs/{run_id} */
    public ApiResponse getRun(ApiRequest request) { return call("GetRun", "GET", "/v1/runs/{run_id}", "application/json", request); }
    public CompletableFuture<ApiResponse> getRunAsync(ApiRequest request) { return async(() -> getRun(request)); }
    /** POST /v1/runs/{run_id}/steps/{ordinal}/approve */
    public ApiResponse approveStep(ApiRequest request) { return call("ApproveStep", "POST", "/v1/runs/{run_id}/steps/{ordinal}/approve", "application/json", request); }
    public CompletableFuture<ApiResponse> approveStepAsync(ApiRequest request) { return async(() -> approveStep(request)); }
    /** POST /v1/search */
    public ApiResponse hybridSearch(ApiRequest request) { return call("HybridSearch", "POST", "/v1/search", "application/json", request); }
    public CompletableFuture<ApiResponse> hybridSearchAsync(ApiRequest request) { return async(() -> hybridSearch(request)); }
    /** GET /v1/sessions/{id} */
    public ApiResponse getSession(ApiRequest request) { return call("GetSession", "GET", "/v1/sessions/{id}", "application/json", request); }
    public CompletableFuture<ApiResponse> getSessionAsync(ApiRequest request) { return async(() -> getSession(request)); }
    /** POST /v1/sessions/{id}/close */
    public ApiResponse closeSession(ApiRequest request) { return call("CloseSession", "POST", "/v1/sessions/{id}/close", "application/json", request); }
    public CompletableFuture<ApiResponse> closeSessionAsync(ApiRequest request) { return async(() -> closeSession(request)); }
    /** POST /v1/sessions/{id}/turns */
    public ApiResponse turn(ApiRequest request) { return call("Turn", "POST", "/v1/sessions/{id}/turns", "application/json", request); }
    public CompletableFuture<ApiResponse> turnAsync(ApiRequest request) { return async(() -> turn(request)); }
    /** POST /v1/sessions/{id}/turns/stream */
    public void turnStream(ApiRequest request, Consumer<ApiResponse> onPart) { stream("TurnStream", "POST", "/v1/sessions/{id}/turns/stream", "application/json", request, onPart); }
    public CompletableFuture<Void> turnStreamAsync(ApiRequest request, Consumer<ApiResponse> onPart) { return async(() -> { turnStream(request, onPart); return null; }); }
    /** POST /v1/shapes */
    public ApiResponse applyShape(ApiRequest request) { return call("ApplyShape", "POST", "/v1/shapes", "text/yaml", request); }
    public CompletableFuture<ApiResponse> applyShapeAsync(ApiRequest request) { return async(() -> applyShape(request)); }
    /** PUT /v1/sources */
    public ApiResponse putSource(ApiRequest request) { return call("PutSource", "PUT", "/v1/sources", "application/octet-stream", request); }
    public CompletableFuture<ApiResponse> putSourceAsync(ApiRequest request) { return async(() -> putSource(request)); }
    /** GET /v1/sources/{source_id} */
    public ApiResponse getSource(ApiRequest request) { return call("GetSource", "GET", "/v1/sources/{source_id}", "application/json", request); }
    public CompletableFuture<ApiResponse> getSourceAsync(ApiRequest request) { return async(() -> getSource(request)); }
    /** POST /v1/versions */
    public ApiResponse createVersion(ApiRequest request) { return call("CreateVersion", "POST", "/v1/versions", "application/json", request); }
    public CompletableFuture<ApiResponse> createVersionAsync(ApiRequest request) { return async(() -> createVersion(request)); }
    /** GET /v1/versions/{version_id}/anchors */
    public ApiResponse getAnchors(ApiRequest request) { return call("GetAnchors", "GET", "/v1/versions/{version_id}/anchors", "application/json", request); }
    public CompletableFuture<ApiResponse> getAnchorsAsync(ApiRequest request) { return async(() -> getAnchors(request)); }
    /** POST /v1/versions/{version_id}/anchors */
    public ApiResponse lockAnchor(ApiRequest request) { return call("LockAnchor", "POST", "/v1/versions/{version_id}/anchors", "application/json", request); }
    public CompletableFuture<ApiResponse> lockAnchorAsync(ApiRequest request) { return async(() -> lockAnchor(request)); }
    /** POST /v1/versions/{version_id}/claims */
    public ApiResponse proposeClaim(ApiRequest request) { return call("ProposeClaim", "POST", "/v1/versions/{version_id}/claims", "application/json", request); }
    public CompletableFuture<ApiResponse> proposeClaimAsync(ApiRequest request) { return async(() -> proposeClaim(request)); }
    /** GET /v1/versions/{version_id}/context */
    public ApiResponse getContext(ApiRequest request) { return call("GetContext", "GET", "/v1/versions/{version_id}/context", "application/json", request); }
    public CompletableFuture<ApiResponse> getContextAsync(ApiRequest request) { return async(() -> getContext(request)); }
    /** GET /v1/versions/{version_id}/counters */
    public ApiResponse getCounters(ApiRequest request) { return call("GetCounters", "GET", "/v1/versions/{version_id}/counters", "application/json", request); }
    public CompletableFuture<ApiResponse> getCountersAsync(ApiRequest request) { return async(() -> getCounters(request)); }
    /** POST /v1/versions/{version_id}/counters */
    public ApiResponse recordCounts(ApiRequest request) { return call("RecordCounts", "POST", "/v1/versions/{version_id}/counters", "application/json", request); }
    public CompletableFuture<ApiResponse> recordCountsAsync(ApiRequest request) { return async(() -> recordCounts(request)); }
    /** GET /v1/versions/{version_id}/digests */
    public ApiResponse getDigests(ApiRequest request) { return call("GetDigests", "GET", "/v1/versions/{version_id}/digests", "application/json", request); }
    public CompletableFuture<ApiResponse> getDigestsAsync(ApiRequest request) { return async(() -> getDigests(request)); }
    /** PUT /v1/versions/{version_id}/digests */
    public ApiResponse upsertDigest(ApiRequest request) { return call("UpsertDigest", "PUT", "/v1/versions/{version_id}/digests", "application/json", request); }
    public CompletableFuture<ApiResponse> upsertDigestAsync(ApiRequest request) { return async(() -> upsertDigest(request)); }
    /** POST /v1/versions/{version_id}/events */
    public ApiResponse appendEvents(ApiRequest request) { return call("AppendEvents", "POST", "/v1/versions/{version_id}/events", "application/json", request); }
    public CompletableFuture<ApiResponse> appendEventsAsync(ApiRequest request) { return async(() -> appendEvents(request)); }
    /** GET /v1/versions/{version_id}/facts */
    public ApiResponse getFacts(ApiRequest request) { return call("GetFacts", "GET", "/v1/versions/{version_id}/facts", "application/json", request); }
    public CompletableFuture<ApiResponse> getFactsAsync(ApiRequest request) { return async(() -> getFacts(request)); }
    /** GET /v1/versions/{version_id}/findings */
    public ApiResponse getFindings(ApiRequest request) { return call("GetFindings", "GET", "/v1/versions/{version_id}/findings", "application/json", request); }
    public CompletableFuture<ApiResponse> getFindingsAsync(ApiRequest request) { return async(() -> getFindings(request)); }
    /** POST /v1/versions/{version_id}/findings */
    public ApiResponse recordFindings(ApiRequest request) { return call("RecordFindings", "POST", "/v1/versions/{version_id}/findings", "application/json", request); }
    public CompletableFuture<ApiResponse> recordFindingsAsync(ApiRequest request) { return async(() -> recordFindings(request)); }
    /** GET /v1/versions/{version_id}/head */
    public ApiResponse getHead(ApiRequest request) { return call("GetHead", "GET", "/v1/versions/{version_id}/head", "application/json", request); }
    public CompletableFuture<ApiResponse> getHeadAsync(ApiRequest request) { return async(() -> getHead(request)); }
    /** POST /v1/versions/{version_id}/ingests */
    public ApiResponse recordIngest(ApiRequest request) { return call("RecordIngest", "POST", "/v1/versions/{version_id}/ingests", "application/json", request); }
    public CompletableFuture<ApiResponse> recordIngestAsync(ApiRequest request) { return async(() -> recordIngest(request)); }
    /** GET /v1/versions/{version_id}/lineage */
    public ApiResponse getLineage(ApiRequest request) { return call("GetLineage", "GET", "/v1/versions/{version_id}/lineage", "application/json", request); }
    public CompletableFuture<ApiResponse> getLineageAsync(ApiRequest request) { return async(() -> getLineage(request)); }
    /** GET /v1/versions/{version_id}/promises */
    public ApiResponse getPromises(ApiRequest request) { return call("GetPromises", "GET", "/v1/versions/{version_id}/promises", "application/json", request); }
    public CompletableFuture<ApiResponse> getPromisesAsync(ApiRequest request) { return async(() -> getPromises(request)); }
    /** POST /v1/versions/{version_id}/promises */
    public ApiResponse openPromise(ApiRequest request) { return call("OpenPromise", "POST", "/v1/versions/{version_id}/promises", "application/json", request); }
    public CompletableFuture<ApiResponse> openPromiseAsync(ApiRequest request) { return async(() -> openPromise(request)); }
    /** POST /v1/versions/{version_id}/promises/{key}/fulfill */
    public ApiResponse fulfillPromise(ApiRequest request) { return call("FulfillPromise", "POST", "/v1/versions/{version_id}/promises/{key}/fulfill", "application/json", request); }
    public CompletableFuture<ApiResponse> fulfillPromiseAsync(ApiRequest request) { return async(() -> fulfillPromise(request)); }
    /** GET /version */
    public ApiResponse versionInfo(ApiRequest request) { return call("VersionInfo", "GET", "/version", "application/json", request); }
    public CompletableFuture<ApiResponse> versionInfoAsync(ApiRequest request) { return async(() -> versionInfo(request)); }
}
