# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from munarium_client._proto.mmp.v1 import admin_pb2 as mmp_dot_v1_dot_admin__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mmp/v1/admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdminServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTenant = channel.unary_unary(
                '/mmp.v1.AdminService/CreateTenant',
                request_serializer=mmp_dot_v1_dot_admin__pb2.CreateTenantRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_admin__pb2.CreateTenantResponse.FromString,
                _registered_method=True)
        self.ListTenants = channel.unary_unary(
                '/mmp.v1.AdminService/ListTenants',
                request_serializer=mmp_dot_v1_dot_admin__pb2.ListTenantsRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_admin__pb2.ListTenantsResponse.FromString,
                _registered_method=True)
        self.Usage = channel.unary_unary(
                '/mmp.v1.AdminService/Usage',
                request_serializer=mmp_dot_v1_dot_admin__pb2.UsageRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_admin__pb2.UsageResponse.FromString,
                _registered_method=True)
        self.IssueAccessToken = channel.unary_unary(
                '/mmp.v1.AdminService/IssueAccessToken',
                request_serializer=mmp_dot_v1_dot_admin__pb2.IssueAccessTokenRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_admin__pb2.IssueAccessTokenResponse.FromString,
                _registered_method=True)
        self.ListAccessTokens = channel.unary_unary(
                '/mmp.v1.AdminService/ListAccessTokens',
                request_serializer=mmp_dot_v1_dot_admin__pb2.ListAccessTokensRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_admin__pb2.ListAccessTokensResponse.FromString,
                _registered_method=True)
        self.RevokeAccessToken = channel.unary_unary(
                '/mmp.v1.AdminService/RevokeAccessToken',
                request_serializer=mmp_dot_v1_dot_admin__pb2.RevokeAccessTokenRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_admin__pb2.RevokeAccessTokenResponse.FromString,
                _registered_method=True)


class AdminServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateTenant(self, request, context):
        """Tenant lifecycle: declared, UNIMPLEMENTED (see header).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTenants(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Usage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IssueAccessToken(self, request, context):
        """Access tokens: SERVED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAccessTokens(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeAccessToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTenant,
                    request_deserializer=mmp_dot_v1_dot_admin__pb2.CreateTenantRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_admin__pb2.CreateTenantResponse.SerializeToString,
            ),
            'ListTenants': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTenants,
                    request_deserializer=mmp_dot_v1_dot_admin__pb2.ListTenantsRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_admin__pb2.ListTenantsResponse.SerializeToString,
            ),
            'Usage': grpc.unary_unary_rpc_method_handler(
                    servicer.Usage,
                    request_deserializer=mmp_dot_v1_dot_admin__pb2.UsageRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_admin__pb2.UsageResponse.SerializeToString,
            ),
            'IssueAccessToken': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueAccessToken,
                    request_deserializer=mmp_dot_v1_dot_admin__pb2.IssueAccessTokenRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_admin__pb2.IssueAccessTokenResponse.SerializeToString,
            ),
            'ListAccessTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccessTokens,
                    request_deserializer=mmp_dot_v1_dot_admin__pb2.ListAccessTokensRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_admin__pb2.ListAccessTokensResponse.SerializeToString,
            ),
            'RevokeAccessToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeAccessToken,
                    request_deserializer=mmp_dot_v1_dot_admin__pb2.RevokeAccessTokenRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_admin__pb2.RevokeAccessTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mmp.v1.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mmp.v1.AdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.AdminService/CreateTenant',
            mmp_dot_v1_dot_admin__pb2.CreateTenantRequest.SerializeToString,
            mmp_dot_v1_dot_admin__pb2.CreateTenantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTenants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.AdminService/ListTenants',
            mmp_dot_v1_dot_admin__pb2.ListTenantsRequest.SerializeToString,
            mmp_dot_v1_dot_admin__pb2.ListTenantsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Usage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.AdminService/Usage',
            mmp_dot_v1_dot_admin__pb2.UsageRequest.SerializeToString,
            mmp_dot_v1_dot_admin__pb2.UsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IssueAccessToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.AdminService/IssueAccessToken',
            mmp_dot_v1_dot_admin__pb2.IssueAccessTokenRequest.SerializeToString,
            mmp_dot_v1_dot_admin__pb2.IssueAccessTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAccessTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.AdminService/ListAccessTokens',
            mmp_dot_v1_dot_admin__pb2.ListAccessTokensRequest.SerializeToString,
            mmp_dot_v1_dot_admin__pb2.ListAccessTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeAccessToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.AdminService/RevokeAccessToken',
            mmp_dot_v1_dot_admin__pb2.RevokeAccessTokenRequest.SerializeToString,
            mmp_dot_v1_dot_admin__pb2.RevokeAccessTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
