# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mmp/v1/common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'mmp/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13mmp/v1/common.proto\x12\x06mmp.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1e\n\tTenantRef\x12\x11\n\ttenant_id\x18\x01 \x01(\t\" \n\nVersionRef\x12\x12\n\nversion_id\x18\x01 \x01(\t\"|\n\x0bGateFinding\x12\x0f\n\x07rule_id\x18\x01 \x01(\t\x12\"\n\x08severity\x18\x02 \x01(\x0e\x32\x10.mmp.v1.Severity\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x12\n\nscope_path\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65tail_json\x18\x05 \x01(\t\"w\n\x0fPolicyRejection\x12\x14\n\x0cproblem_type\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\x12%\n\x08\x66indings\x18\x03 \x03(\x0b\x32\x13.mmp.v1.GateFinding\x12\x17\n\x0fpolicy_citation\x18\x04 \x01(\t\"4\n\x0bPageRequest\x12\x11\n\tpage_size\x18\x01 \x01(\r\x12\x12\n\npage_token\x18\x02 \x01(\t\"\'\n\x0cPageResponse\x12\x17\n\x0fnext_page_token\x18\x01 \x01(\t\"\xf0\x01\n\x12ProvenanceEnvelope\x12\x11\n\tchunk_ids\x18\x01 \x03(\t\x12\x1d\n\x15source_content_hashes\x18\x02 \x03(\t\x12\x15\n\rindex_version\x18\x03 \x01(\t\x12\x17\n\x0f\x65vent_watermark\x18\x04 \x01(\x04\x12\x1c\n\x14provider_fingerprint\x18\x05 \x01(\t\x12\x30\n\x0cgenerated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nsource_ids\x18\x07 \x03(\t\x12\x14\n\x0csource_paths\x18\x08 \x03(\t*a\n\x0b\x43laimStatus\x12\x1c\n\x18\x43LAIM_STATUS_UNSPECIFIED\x10\x00\x12\x19\n\x15\x43LAIM_STATUS_ACCEPTED\x10\x01\x12\x19\n\x15\x43LAIM_STATUS_DISPUTED\x10\x02*^\n\x08Severity\x12\x18\n\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n\rSEVERITY_INFO\x10\x01\x12\x11\n\rSEVERITY_WARN\x10\x02\x12\x12\n\x0eSEVERITY_BLOCK\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mmp.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLAIMSTATUS']._serialized_start=715
  _globals['_CLAIMSTATUS']._serialized_end=812
  _globals['_SEVERITY']._serialized_start=814
  _globals['_SEVERITY']._serialized_end=908
  _globals['_TENANTREF']._serialized_start=64
  _globals['_TENANTREF']._serialized_end=94
  _globals['_VERSIONREF']._serialized_start=96
  _globals['_VERSIONREF']._serialized_end=128
  _globals['_GATEFINDING']._serialized_start=130
  _globals['_GATEFINDING']._serialized_end=254
  _globals['_POLICYREJECTION']._serialized_start=256
  _globals['_POLICYREJECTION']._serialized_end=375
  _globals['_PAGEREQUEST']._serialized_start=377
  _globals['_PAGEREQUEST']._serialized_end=429
  _globals['_PAGERESPONSE']._serialized_start=431
  _globals['_PAGERESPONSE']._serialized_end=470
  _globals['_PROVENANCEENVELOPE']._serialized_start=473
  _globals['_PROVENANCEENVELOPE']._serialized_end=713
# @@protoc_insertion_point(module_scope)
