# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from munarium_client._proto.mmp.v1 import command_pb2 as mmp_dot_v1_dot_command__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mmp/v1/command_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CommandServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateVersion = channel.unary_unary(
                '/mmp.v1.CommandService/CreateVersion',
                request_serializer=mmp_dot_v1_dot_command__pb2.CreateVersionRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_command__pb2.CreateVersionResponse.FromString,
                _registered_method=True)
        self.ProposeClaim = channel.unary_unary(
                '/mmp.v1.CommandService/ProposeClaim',
                request_serializer=mmp_dot_v1_dot_command__pb2.ProposeClaimRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_command__pb2.ProposeClaimResponse.FromString,
                _registered_method=True)
        self.AppendEvents = channel.unary_unary(
                '/mmp.v1.CommandService/AppendEvents',
                request_serializer=mmp_dot_v1_dot_command__pb2.AppendEventsRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_command__pb2.AppendEventsResponse.FromString,
                _registered_method=True)
        self.OpenPromise = channel.unary_unary(
                '/mmp.v1.CommandService/OpenPromise',
                request_serializer=mmp_dot_v1_dot_command__pb2.OpenPromiseRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_command__pb2.OpenPromiseResponse.FromString,
                _registered_method=True)
        self.FulfillPromise = channel.unary_unary(
                '/mmp.v1.CommandService/FulfillPromise',
                request_serializer=mmp_dot_v1_dot_command__pb2.FulfillPromiseRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_command__pb2.FulfillPromiseResponse.FromString,
                _registered_method=True)
        self.LockAnchor = channel.unary_unary(
                '/mmp.v1.CommandService/LockAnchor',
                request_serializer=mmp_dot_v1_dot_command__pb2.LockAnchorRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_command__pb2.LockAnchorResponse.FromString,
                _registered_method=True)
        self.RecordCounts = channel.unary_unary(
                '/mmp.v1.CommandService/RecordCounts',
                request_serializer=mmp_dot_v1_dot_command__pb2.RecordCountsRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_command__pb2.RecordCountsResponse.FromString,
                _registered_method=True)
        self.UpsertDigest = channel.unary_unary(
                '/mmp.v1.CommandService/UpsertDigest',
                request_serializer=mmp_dot_v1_dot_command__pb2.UpsertDigestRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_command__pb2.UpsertDigestResponse.FromString,
                _registered_method=True)


class CommandServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProposeClaim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenPromise(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FulfillPromise(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LockAnchor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordCounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertDigest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommandServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVersion,
                    request_deserializer=mmp_dot_v1_dot_command__pb2.CreateVersionRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_command__pb2.CreateVersionResponse.SerializeToString,
            ),
            'ProposeClaim': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeClaim,
                    request_deserializer=mmp_dot_v1_dot_command__pb2.ProposeClaimRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_command__pb2.ProposeClaimResponse.SerializeToString,
            ),
            'AppendEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEvents,
                    request_deserializer=mmp_dot_v1_dot_command__pb2.AppendEventsRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_command__pb2.AppendEventsResponse.SerializeToString,
            ),
            'OpenPromise': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenPromise,
                    request_deserializer=mmp_dot_v1_dot_command__pb2.OpenPromiseRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_command__pb2.OpenPromiseResponse.SerializeToString,
            ),
            'FulfillPromise': grpc.unary_unary_rpc_method_handler(
                    servicer.FulfillPromise,
                    request_deserializer=mmp_dot_v1_dot_command__pb2.FulfillPromiseRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_command__pb2.FulfillPromiseResponse.SerializeToString,
            ),
            'LockAnchor': grpc.unary_unary_rpc_method_handler(
                    servicer.LockAnchor,
                    request_deserializer=mmp_dot_v1_dot_command__pb2.LockAnchorRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_command__pb2.LockAnchorResponse.SerializeToString,
            ),
            'RecordCounts': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordCounts,
                    request_deserializer=mmp_dot_v1_dot_command__pb2.RecordCountsRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_command__pb2.RecordCountsResponse.SerializeToString,
            ),
            'UpsertDigest': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertDigest,
                    request_deserializer=mmp_dot_v1_dot_command__pb2.UpsertDigestRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_command__pb2.UpsertDigestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mmp.v1.CommandService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mmp.v1.CommandService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CommandService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.CommandService/CreateVersion',
            mmp_dot_v1_dot_command__pb2.CreateVersionRequest.SerializeToString,
            mmp_dot_v1_dot_command__pb2.CreateVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProposeClaim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.CommandService/ProposeClaim',
            mmp_dot_v1_dot_command__pb2.ProposeClaimRequest.SerializeToString,
            mmp_dot_v1_dot_command__pb2.ProposeClaimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.CommandService/AppendEvents',
            mmp_dot_v1_dot_command__pb2.AppendEventsRequest.SerializeToString,
            mmp_dot_v1_dot_command__pb2.AppendEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenPromise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.CommandService/OpenPromise',
            mmp_dot_v1_dot_command__pb2.OpenPromiseRequest.SerializeToString,
            mmp_dot_v1_dot_command__pb2.OpenPromiseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FulfillPromise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.CommandService/FulfillPromise',
            mmp_dot_v1_dot_command__pb2.FulfillPromiseRequest.SerializeToString,
            mmp_dot_v1_dot_command__pb2.FulfillPromiseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LockAnchor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.CommandService/LockAnchor',
            mmp_dot_v1_dot_command__pb2.LockAnchorRequest.SerializeToString,
            mmp_dot_v1_dot_command__pb2.LockAnchorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordCounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.CommandService/RecordCounts',
            mmp_dot_v1_dot_command__pb2.RecordCountsRequest.SerializeToString,
            mmp_dot_v1_dot_command__pb2.RecordCountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertDigest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.CommandService/UpsertDigest',
            mmp_dot_v1_dot_command__pb2.UpsertDigestRequest.SerializeToString,
            mmp_dot_v1_dot_command__pb2.UpsertDigestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
