# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mmp/v1/ingest.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'mmp/v1/ingest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13mmp/v1/ingest.proto\x12\x06mmp.v1\"R\n\x10PutSourceRequest\x12&\n\x06header\x18\x01 \x01(\x0b\x32\x14.mmp.v1.SourceHeaderH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x42\x05\n\x03msg\"`\n\x0cSourceHeader\x12\x17\n\x0f\x64\x65\x63lared_sha256\x18\x01 \x01(\t\x12\x12\n\nmedia_type\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x11\n\tshape_ref\x18\x04 \x01(\t\"h\n\x11PutSourceResponse\x12\x14\n\x0c\x63ontent_hash\x18\x01 \x01(\t\x12\x11\n\tbytes_len\x18\x02 \x01(\x04\x12\x17\n\x0f\x61lready_existed\x18\x03 \x01(\x08\x12\x11\n\tsource_id\x18\x04 \x01(\t\"i\n\x13RecordIngestRequest\x12\x12\n\nversion_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontent_hash\x18\x02 \x01(\t\x12\x11\n\tshape_ref\x18\x03 \x01(\t\x12\x15\n\rmetadata_json\x18\x04 \x01(\t\"5\n\x14RecordIngestResponse\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x0b\n\x03seq\x18\x02 \x01(\x04\"h\n\nIngestFile\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x12\n\nmedia_type\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12\x0e\n\x06sha256\x18\x04 \x01(\t\x12\x13\n\x0b\x63ollections\x18\x05 \x03(\t\"7\n\x12IngestFilesRequest\x12!\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x12.mmp.v1.IngestFile\"u\n\x0cIngestResult\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12\x0e\n\x06sha256\x18\x03 \x01(\t\x12\x0f\n\x07\x65xisted\x18\x04 \x01(\x08\x12\x10\n\x08\x62ound_to\x18\x05 \x03(\t\x12\r\n\x05\x65rror\x18\x06 \x01(\t\"<\n\x13IngestFilesResponse\x12%\n\x07results\x18\x01 \x03(\x0b\x32\x14.mmp.v1.IngestResult2\xe6\x01\n\rIngestService\x12\x42\n\tPutSource\x12\x18.mmp.v1.PutSourceRequest\x1a\x19.mmp.v1.PutSourceResponse(\x01\x12I\n\x0cRecordIngest\x12\x1b.mmp.v1.RecordIngestRequest\x1a\x1c.mmp.v1.RecordIngestResponse\x12\x46\n\x0bIngestFiles\x12\x1a.mmp.v1.IngestFilesRequest\x1a\x1b.mmp.v1.IngestFilesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mmp.v1.ingest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUTSOURCEREQUEST']._serialized_start=31
  _globals['_PUTSOURCEREQUEST']._serialized_end=113
  _globals['_SOURCEHEADER']._serialized_start=115
  _globals['_SOURCEHEADER']._serialized_end=211
  _globals['_PUTSOURCERESPONSE']._serialized_start=213
  _globals['_PUTSOURCERESPONSE']._serialized_end=317
  _globals['_RECORDINGESTREQUEST']._serialized_start=319
  _globals['_RECORDINGESTREQUEST']._serialized_end=424
  _globals['_RECORDINGESTRESPONSE']._serialized_start=426
  _globals['_RECORDINGESTRESPONSE']._serialized_end=479
  _globals['_INGESTFILE']._serialized_start=481
  _globals['_INGESTFILE']._serialized_end=585
  _globals['_INGESTFILESREQUEST']._serialized_start=587
  _globals['_INGESTFILESREQUEST']._serialized_end=642
  _globals['_INGESTRESULT']._serialized_start=644
  _globals['_INGESTRESULT']._serialized_end=761
  _globals['_INGESTFILESRESPONSE']._serialized_start=763
  _globals['_INGESTFILESRESPONSE']._serialized_end=823
  _globals['_INGESTSERVICE']._serialized_start=826
  _globals['_INGESTSERVICE']._serialized_end=1056
# @@protoc_insertion_point(module_scope)
