# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from munarium_client._proto.mmp.v1 import ingest_pb2 as mmp_dot_v1_dot_ingest__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mmp/v1/ingest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IngestServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutSource = channel.stream_unary(
                '/mmp.v1.IngestService/PutSource',
                request_serializer=mmp_dot_v1_dot_ingest__pb2.PutSourceRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_ingest__pb2.PutSourceResponse.FromString,
                _registered_method=True)
        self.RecordIngest = channel.unary_unary(
                '/mmp.v1.IngestService/RecordIngest',
                request_serializer=mmp_dot_v1_dot_ingest__pb2.RecordIngestRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_ingest__pb2.RecordIngestResponse.FromString,
                _registered_method=True)
        self.IngestFiles = channel.unary_unary(
                '/mmp.v1.IngestService/IngestFiles',
                request_serializer=mmp_dot_v1_dot_ingest__pb2.IngestFilesRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_ingest__pb2.IngestFilesResponse.FromString,
                _registered_method=True)


class IngestServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PutSource(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordIngest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestFiles(self, request, context):
        """REST twin:
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutSource': grpc.stream_unary_rpc_method_handler(
                    servicer.PutSource,
                    request_deserializer=mmp_dot_v1_dot_ingest__pb2.PutSourceRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_ingest__pb2.PutSourceResponse.SerializeToString,
            ),
            'RecordIngest': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordIngest,
                    request_deserializer=mmp_dot_v1_dot_ingest__pb2.RecordIngestRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_ingest__pb2.RecordIngestResponse.SerializeToString,
            ),
            'IngestFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestFiles,
                    request_deserializer=mmp_dot_v1_dot_ingest__pb2.IngestFilesRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_ingest__pb2.IngestFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mmp.v1.IngestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mmp.v1.IngestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IngestService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PutSource(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/mmp.v1.IngestService/PutSource',
            mmp_dot_v1_dot_ingest__pb2.PutSourceRequest.SerializeToString,
            mmp_dot_v1_dot_ingest__pb2.PutSourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordIngest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.IngestService/RecordIngest',
            mmp_dot_v1_dot_ingest__pb2.RecordIngestRequest.SerializeToString,
            mmp_dot_v1_dot_ingest__pb2.RecordIngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.IngestService/IngestFiles',
            mmp_dot_v1_dot_ingest__pb2.IngestFilesRequest.SerializeToString,
            mmp_dot_v1_dot_ingest__pb2.IngestFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
