# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from munarium_client._proto.mmp.v1 import query_pb2 as mmp_dot_v1_dot_query__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mmp/v1/query_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueryServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHead = channel.unary_unary(
                '/mmp.v1.QueryService/GetHead',
                request_serializer=mmp_dot_v1_dot_query__pb2.GetHeadRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_query__pb2.GetHeadResponse.FromString,
                _registered_method=True)
        self.GetClaim = channel.unary_unary(
                '/mmp.v1.QueryService/GetClaim',
                request_serializer=mmp_dot_v1_dot_query__pb2.GetClaimRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_query__pb2.GetClaimResponse.FromString,
                _registered_method=True)
        self.SliceFacts = channel.unary_unary(
                '/mmp.v1.QueryService/SliceFacts',
                request_serializer=mmp_dot_v1_dot_query__pb2.SliceFactsRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_query__pb2.SliceFactsResponse.FromString,
                _registered_method=True)
        self.GetLineage = channel.unary_unary(
                '/mmp.v1.QueryService/GetLineage',
                request_serializer=mmp_dot_v1_dot_query__pb2.GetLineageRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_query__pb2.GetLineageResponse.FromString,
                _registered_method=True)
        self.ListAnchors = channel.unary_unary(
                '/mmp.v1.QueryService/ListAnchors',
                request_serializer=mmp_dot_v1_dot_query__pb2.ListAnchorsRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_query__pb2.ListAnchorsResponse.FromString,
                _registered_method=True)
        self.ListPromises = channel.unary_unary(
                '/mmp.v1.QueryService/ListPromises',
                request_serializer=mmp_dot_v1_dot_query__pb2.ListPromisesRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_query__pb2.ListPromisesResponse.FromString,
                _registered_method=True)
        self.ComposeContext = channel.unary_unary(
                '/mmp.v1.QueryService/ComposeContext',
                request_serializer=mmp_dot_v1_dot_query__pb2.ComposeContextRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_query__pb2.ComposeContextResponse.FromString,
                _registered_method=True)
        self.CounterTotals = channel.unary_unary(
                '/mmp.v1.QueryService/CounterTotals',
                request_serializer=mmp_dot_v1_dot_query__pb2.CounterTotalsRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_query__pb2.CounterTotalsResponse.FromString,
                _registered_method=True)
        self.ListDigests = channel.unary_unary(
                '/mmp.v1.QueryService/ListDigests',
                request_serializer=mmp_dot_v1_dot_query__pb2.ListDigestsRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_query__pb2.ListDigestsResponse.FromString,
                _registered_method=True)


class QueryServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetHead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClaim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SliceFacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLineage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAnchors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPromises(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComposeContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CounterTotals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDigests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHead': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHead,
                    request_deserializer=mmp_dot_v1_dot_query__pb2.GetHeadRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_query__pb2.GetHeadResponse.SerializeToString,
            ),
            'GetClaim': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClaim,
                    request_deserializer=mmp_dot_v1_dot_query__pb2.GetClaimRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_query__pb2.GetClaimResponse.SerializeToString,
            ),
            'SliceFacts': grpc.unary_unary_rpc_method_handler(
                    servicer.SliceFacts,
                    request_deserializer=mmp_dot_v1_dot_query__pb2.SliceFactsRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_query__pb2.SliceFactsResponse.SerializeToString,
            ),
            'GetLineage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLineage,
                    request_deserializer=mmp_dot_v1_dot_query__pb2.GetLineageRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_query__pb2.GetLineageResponse.SerializeToString,
            ),
            'ListAnchors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAnchors,
                    request_deserializer=mmp_dot_v1_dot_query__pb2.ListAnchorsRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_query__pb2.ListAnchorsResponse.SerializeToString,
            ),
            'ListPromises': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPromises,
                    request_deserializer=mmp_dot_v1_dot_query__pb2.ListPromisesRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_query__pb2.ListPromisesResponse.SerializeToString,
            ),
            'ComposeContext': grpc.unary_unary_rpc_method_handler(
                    servicer.ComposeContext,
                    request_deserializer=mmp_dot_v1_dot_query__pb2.ComposeContextRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_query__pb2.ComposeContextResponse.SerializeToString,
            ),
            'CounterTotals': grpc.unary_unary_rpc_method_handler(
                    servicer.CounterTotals,
                    request_deserializer=mmp_dot_v1_dot_query__pb2.CounterTotalsRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_query__pb2.CounterTotalsResponse.SerializeToString,
            ),
            'ListDigests': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDigests,
                    request_deserializer=mmp_dot_v1_dot_query__pb2.ListDigestsRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_query__pb2.ListDigestsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mmp.v1.QueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mmp.v1.QueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueryService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.QueryService/GetHead',
            mmp_dot_v1_dot_query__pb2.GetHeadRequest.SerializeToString,
            mmp_dot_v1_dot_query__pb2.GetHeadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClaim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.QueryService/GetClaim',
            mmp_dot_v1_dot_query__pb2.GetClaimRequest.SerializeToString,
            mmp_dot_v1_dot_query__pb2.GetClaimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SliceFacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.QueryService/SliceFacts',
            mmp_dot_v1_dot_query__pb2.SliceFactsRequest.SerializeToString,
            mmp_dot_v1_dot_query__pb2.SliceFactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLineage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.QueryService/GetLineage',
            mmp_dot_v1_dot_query__pb2.GetLineageRequest.SerializeToString,
            mmp_dot_v1_dot_query__pb2.GetLineageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAnchors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.QueryService/ListAnchors',
            mmp_dot_v1_dot_query__pb2.ListAnchorsRequest.SerializeToString,
            mmp_dot_v1_dot_query__pb2.ListAnchorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPromises(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.QueryService/ListPromises',
            mmp_dot_v1_dot_query__pb2.ListPromisesRequest.SerializeToString,
            mmp_dot_v1_dot_query__pb2.ListPromisesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComposeContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.QueryService/ComposeContext',
            mmp_dot_v1_dot_query__pb2.ComposeContextRequest.SerializeToString,
            mmp_dot_v1_dot_query__pb2.ComposeContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CounterTotals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.QueryService/CounterTotals',
            mmp_dot_v1_dot_query__pb2.CounterTotalsRequest.SerializeToString,
            mmp_dot_v1_dot_query__pb2.CounterTotalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDigests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.QueryService/ListDigests',
            mmp_dot_v1_dot_query__pb2.ListDigestsRequest.SerializeToString,
            mmp_dot_v1_dot_query__pb2.ListDigestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
