# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from munarium_client._proto.mmp.v1 import runbook_pb2 as mmp_dot_v1_dot_runbook__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mmp/v1/runbook_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RunbookServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ApplyShape = channel.unary_unary(
                '/mmp.v1.RunbookService/ApplyShape',
                request_serializer=mmp_dot_v1_dot_runbook__pb2.ApplyShapeRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_runbook__pb2.ApplyShapeResponse.FromString,
                _registered_method=True)
        self.ApplyRunbook = channel.unary_unary(
                '/mmp.v1.RunbookService/ApplyRunbook',
                request_serializer=mmp_dot_v1_dot_runbook__pb2.ApplyRunbookRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_runbook__pb2.ApplyRunbookResponse.FromString,
                _registered_method=True)
        self.RunRunbook = channel.unary_unary(
                '/mmp.v1.RunbookService/RunRunbook',
                request_serializer=mmp_dot_v1_dot_runbook__pb2.RunRunbookRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_runbook__pb2.RunRunbookResponse.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/mmp.v1.RunbookService/GetRun',
                request_serializer=mmp_dot_v1_dot_runbook__pb2.GetRunRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_runbook__pb2.GetRunResponse.FromString,
                _registered_method=True)
        self.ApproveStep = channel.unary_unary(
                '/mmp.v1.RunbookService/ApproveStep',
                request_serializer=mmp_dot_v1_dot_runbook__pb2.ApproveStepRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_runbook__pb2.ApproveStepResponse.FromString,
                _registered_method=True)
        self.ListRunbooks = channel.unary_unary(
                '/mmp.v1.RunbookService/ListRunbooks',
                request_serializer=mmp_dot_v1_dot_runbook__pb2.ListRunbooksRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_runbook__pb2.ListRunbooksResponse.FromString,
                _registered_method=True)
        self.GetRunbookInfo = channel.unary_unary(
                '/mmp.v1.RunbookService/GetRunbookInfo',
                request_serializer=mmp_dot_v1_dot_runbook__pb2.GetRunbookInfoRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_runbook__pb2.GetRunbookInfoResponse.FromString,
                _registered_method=True)
        self.ValidateRunbook = channel.unary_unary(
                '/mmp.v1.RunbookService/ValidateRunbook',
                request_serializer=mmp_dot_v1_dot_runbook__pb2.ValidateRunbookRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_runbook__pb2.ValidateRunbookResponse.FromString,
                _registered_method=True)
        self.RequestRemoval = channel.unary_unary(
                '/mmp.v1.RunbookService/RequestRemoval',
                request_serializer=mmp_dot_v1_dot_runbook__pb2.RequestRemovalRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_runbook__pb2.RequestRemovalResponse.FromString,
                _registered_method=True)
        self.ConfirmRemoval = channel.unary_unary(
                '/mmp.v1.RunbookService/ConfirmRemoval',
                request_serializer=mmp_dot_v1_dot_runbook__pb2.ConfirmRemovalRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_runbook__pb2.ConfirmRemovalResponse.FromString,
                _registered_method=True)


class RunbookServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ApplyShape(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyRunbook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunRunbook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunbooks(self, request, context):
        """REST twins:
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunbookInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateRunbook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestRemoval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmRemoval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RunbookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ApplyShape': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyShape,
                    request_deserializer=mmp_dot_v1_dot_runbook__pb2.ApplyShapeRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_runbook__pb2.ApplyShapeResponse.SerializeToString,
            ),
            'ApplyRunbook': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyRunbook,
                    request_deserializer=mmp_dot_v1_dot_runbook__pb2.ApplyRunbookRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_runbook__pb2.ApplyRunbookResponse.SerializeToString,
            ),
            'RunRunbook': grpc.unary_unary_rpc_method_handler(
                    servicer.RunRunbook,
                    request_deserializer=mmp_dot_v1_dot_runbook__pb2.RunRunbookRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_runbook__pb2.RunRunbookResponse.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=mmp_dot_v1_dot_runbook__pb2.GetRunRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_runbook__pb2.GetRunResponse.SerializeToString,
            ),
            'ApproveStep': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveStep,
                    request_deserializer=mmp_dot_v1_dot_runbook__pb2.ApproveStepRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_runbook__pb2.ApproveStepResponse.SerializeToString,
            ),
            'ListRunbooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRunbooks,
                    request_deserializer=mmp_dot_v1_dot_runbook__pb2.ListRunbooksRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_runbook__pb2.ListRunbooksResponse.SerializeToString,
            ),
            'GetRunbookInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunbookInfo,
                    request_deserializer=mmp_dot_v1_dot_runbook__pb2.GetRunbookInfoRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_runbook__pb2.GetRunbookInfoResponse.SerializeToString,
            ),
            'ValidateRunbook': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateRunbook,
                    request_deserializer=mmp_dot_v1_dot_runbook__pb2.ValidateRunbookRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_runbook__pb2.ValidateRunbookResponse.SerializeToString,
            ),
            'RequestRemoval': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestRemoval,
                    request_deserializer=mmp_dot_v1_dot_runbook__pb2.RequestRemovalRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_runbook__pb2.RequestRemovalResponse.SerializeToString,
            ),
            'ConfirmRemoval': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmRemoval,
                    request_deserializer=mmp_dot_v1_dot_runbook__pb2.ConfirmRemovalRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_runbook__pb2.ConfirmRemovalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mmp.v1.RunbookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mmp.v1.RunbookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RunbookService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ApplyShape(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.RunbookService/ApplyShape',
            mmp_dot_v1_dot_runbook__pb2.ApplyShapeRequest.SerializeToString,
            mmp_dot_v1_dot_runbook__pb2.ApplyShapeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyRunbook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.RunbookService/ApplyRunbook',
            mmp_dot_v1_dot_runbook__pb2.ApplyRunbookRequest.SerializeToString,
            mmp_dot_v1_dot_runbook__pb2.ApplyRunbookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunRunbook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.RunbookService/RunRunbook',
            mmp_dot_v1_dot_runbook__pb2.RunRunbookRequest.SerializeToString,
            mmp_dot_v1_dot_runbook__pb2.RunRunbookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.RunbookService/GetRun',
            mmp_dot_v1_dot_runbook__pb2.GetRunRequest.SerializeToString,
            mmp_dot_v1_dot_runbook__pb2.GetRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.RunbookService/ApproveStep',
            mmp_dot_v1_dot_runbook__pb2.ApproveStepRequest.SerializeToString,
            mmp_dot_v1_dot_runbook__pb2.ApproveStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRunbooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.RunbookService/ListRunbooks',
            mmp_dot_v1_dot_runbook__pb2.ListRunbooksRequest.SerializeToString,
            mmp_dot_v1_dot_runbook__pb2.ListRunbooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunbookInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.RunbookService/GetRunbookInfo',
            mmp_dot_v1_dot_runbook__pb2.GetRunbookInfoRequest.SerializeToString,
            mmp_dot_v1_dot_runbook__pb2.GetRunbookInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateRunbook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.RunbookService/ValidateRunbook',
            mmp_dot_v1_dot_runbook__pb2.ValidateRunbookRequest.SerializeToString,
            mmp_dot_v1_dot_runbook__pb2.ValidateRunbookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestRemoval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.RunbookService/RequestRemoval',
            mmp_dot_v1_dot_runbook__pb2.RequestRemovalRequest.SerializeToString,
            mmp_dot_v1_dot_runbook__pb2.RequestRemovalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmRemoval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.RunbookService/ConfirmRemoval',
            mmp_dot_v1_dot_runbook__pb2.ConfirmRemovalRequest.SerializeToString,
            mmp_dot_v1_dot_runbook__pb2.ConfirmRemovalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
