# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from munarium_client._proto.mmp.v1 import session_pb2 as mmp_dot_v1_dot_session__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mmp/v1/session_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SessionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/mmp.v1.SessionService/CreateSession',
                request_serializer=mmp_dot_v1_dot_session__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_session__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.Turn = channel.unary_unary(
                '/mmp.v1.SessionService/Turn',
                request_serializer=mmp_dot_v1_dot_session__pb2.TurnRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_session__pb2.TurnResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/mmp.v1.SessionService/GetSession',
                request_serializer=mmp_dot_v1_dot_session__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_session__pb2.GetSessionResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/mmp.v1.SessionService/CloseSession',
                request_serializer=mmp_dot_v1_dot_session__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=mmp_dot_v1_dot_session__pb2.GetSessionResponse.FromString,
                _registered_method=True)


class SessionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Turn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Idempotent; closing a closed/expired session returns its state unchanged.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=mmp_dot_v1_dot_session__pb2.CreateSessionRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_session__pb2.CreateSessionResponse.SerializeToString,
            ),
            'Turn': grpc.unary_unary_rpc_method_handler(
                    servicer.Turn,
                    request_deserializer=mmp_dot_v1_dot_session__pb2.TurnRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_session__pb2.TurnResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=mmp_dot_v1_dot_session__pb2.GetSessionRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_session__pb2.GetSessionResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=mmp_dot_v1_dot_session__pb2.CloseSessionRequest.FromString,
                    response_serializer=mmp_dot_v1_dot_session__pb2.GetSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mmp.v1.SessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mmp.v1.SessionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.SessionService/CreateSession',
            mmp_dot_v1_dot_session__pb2.CreateSessionRequest.SerializeToString,
            mmp_dot_v1_dot_session__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Turn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.SessionService/Turn',
            mmp_dot_v1_dot_session__pb2.TurnRequest.SerializeToString,
            mmp_dot_v1_dot_session__pb2.TurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.SessionService/GetSession',
            mmp_dot_v1_dot_session__pb2.GetSessionRequest.SerializeToString,
            mmp_dot_v1_dot_session__pb2.GetSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmp.v1.SessionService/CloseSession',
            mmp_dot_v1_dot_session__pb2.CloseSessionRequest.SerializeToString,
            mmp_dot_v1_dot_session__pb2.GetSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
