# SPDX-License-Identifier: Apache-2.0
"""Generate the complete Server API's named RPC contract from OpenAPI.

Payloads retain the normative JSON/YAML/binary representation. In particular,
JSON null versus an omitted property and 64-bit integers must survive both
transports. This is not an HTTP proxy: every RPC selects a fixed local handler.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ALIASES = {
    "answer": "compose_answer", "search": "search_collection",
    "get": "get_collection_vocabulary", "put": "replace_collection_vocabulary",
    "patch": "update_collection_vocabulary", "refresh": "refresh_collection_vocabulary",
    "get_revision": "get_vocabulary_revision", "get_settings": "get_vocabulary_settings",
    "put_settings": "replace_vocabulary_settings",
}


def operations() -> list[dict]:
    spec = json.loads((ROOT / "server/docs/api/openapi.json").read_text(encoding="utf-8"))
    result = []
    for path, item in sorted(spec["paths"].items()):
        for method, op in sorted(item.items()):
            if method not in {"get", "post", "put", "patch", "delete", "head", "options"}:
                continue
            name = op["operationId"]
            if path.startswith("/v1.2/"):
                name = ALIASES.get(name, name)
            content = op.get("requestBody", {}).get("content", {})
            result.append(dict(name=name, rpc="".join(p.title() for p in name.split("_")),
                               method=method.upper(), path=path,
                               content_type=next(iter(content), "application/json"),
                               streaming=path.endswith("/turns/stream") or any("text/event-stream" in r.get("content", {})
                                             for r in op.get("responses", {}).values())))
    assert len({op["rpc"] for op in result}) == len(result), "RPC names must be unique"
    return result


def outputs() -> dict[str, str]:
    ops = operations()
    version = json.loads((ROOT / "server/docs/api/openapi.json").read_text(encoding="utf-8"))["info"]["version"]
    proto = '''// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate_server_api.py from the normative OpenAPI.
syntax = "proto3";
package mmp.v1;

// Path and query values are unescaped; the server encodes them as components.
// Authentication, uid and idempotency-key use normal gRPC metadata, never here.
message ServerApiRequest {
  map<string, string> path_parameters = 1;
  repeated ServerApiParameter query_parameters = 2;
  bytes body = 3;
  // Empty chooses the operation's declared request media type.
  string content_type = 4;
  // Only x-filename, x-content-sha256 and x-shape-ref are accepted.
  map<string, string> source_headers = 5;
}
message ServerApiParameter { string name = 1; string value = 2; }
// JSON is UTF-8 bytes rather than google.protobuf.Struct: uint64, omitted
// fields and explicit null must round-trip without precision/presence loss.
// Streaming RPCs emit body fragments incrementally, including SSE delimiters.
message ServerApiResponse {
  uint32 status = 1;
  string content_type = 2;
  bytes body = 3;
}
service ServerApiService {
'''
    rust = "// SPDX-License-Identifier: Apache-2.0\n// Generated by scripts/generate_server_api.py.\nuse super::*;\n#[tonic::async_trait]\nimpl pb::server_api_service_server::ServerApiService for ServerApiSvc {\n"
    for op in ops:
        stream = "stream " if op["streaming"] else ""
        proto += f'  // {op["method"]} {op["path"]}\n  rpc {op["rpc"]}(ServerApiRequest) returns ({stream}ServerApiResponse);\n'
        output = "Self::" + op["rpc"] + "Stream" if op["streaming"] else "pb::ServerApiResponse"
        if op["streaming"]:
            rust += f'    type {op["rpc"]}Stream = ApiStream;\n'
        fn = "stream" if op["streaming"] else "unary"
        rust += f'''    async fn {op["name"]}(&self, request: Request<pb::ServerApiRequest>) -> Result<Response<{output}>, Status> {{
        self.{fn}(request, "{op['method']}", "{op['path']}", "{op['content_type']}").await
    }}
'''
    proto += "}\n"
    rust += "}\n"
    python = '''# SPDX-License-Identifier: Apache-2.0
# Generated by scripts/generate_server_api.py; payload schemas are in OpenAPI.
from __future__ import annotations

from collections.abc import AsyncIterator, Iterator

from ._server_api import ApiRequest, ApiResponse, BaseAsyncServerApi, BaseServerApi


class ServerApiClient(BaseServerApi):
'''
    python_async = "\nclass AsyncServerApiClient(BaseAsyncServerApi):\n"
    client_rust = "// SPDX-License-Identifier: Apache-2.0\n// Generated by scripts/generate_server_api.py.\nuse super::*;\nimpl ServerApiClient {\n"
    dotnet = "// SPDX-License-Identifier: Apache-2.0\n// Generated by scripts/generate_server_api.py.\n#nullable enable\nnamespace Ioka.Munarium.Client;\npublic sealed partial class ServerApiClient {\n"
    java = '''// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate_server_api.py.
package io.ioka.munarium.client;
import java.util.concurrent.CompletableFuture;
import java.util.function.Consumer;
public final class ServerApiClient extends ServerApiTransport {
    public ServerApiClient(MunariumClientOptions options, boolean grpc) { super(options, grpc); }
'''
    for op in ops:
        args = ", ".join(json.dumps(op[k]) for k in ("rpc", "method", "path", "content_type"))
        stream = op["streaming"]
        pyargs = "".join("            " + json.dumps(op[k]) + ",\n" for k in ("rpc", "method", "path", "content_type")) + "            request,\n"
        params = "(\n        self,\n        request: ApiRequest | None = None,\n    )"
        python += f'    def {op["name"]}{params} -> {"Iterator[ApiResponse]" if stream else "ApiResponse"}:\n'
        python += f'        """{op["method"]} {op["path"]}"""\n        return self._{"stream" if stream else "call"}(\n{pyargs}        )\n\n'
        python_async += f'    async def {op["name"]}{params} -> {"AsyncIterator[ApiResponse]" if stream else "ApiResponse"}:\n'
        python_async += f'        """{op["method"]} {op["path"]}"""\n'
        python_async += (f'        async for part in self._stream(\n{pyargs}        ):\n            yield part\n\n' if stream else f'        return await self._call(\n{pyargs}        )\n\n')
        client_rust += f'    /// {op["method"]} {op["path"]}\n    pub async fn {op["name"]}(&self, request: ApiRequest) -> Result<{"ApiStream" if stream else "ApiResponse"}> {{\n        self.{"stream" if stream else "call"}({args}, request).await\n    }}\n'
        dotnet += f'    /// <summary>{op["method"]} {op["path"]}</summary>\n'
        if stream:
            dotnet += f'    public IAsyncEnumerable<ApiResponse> {op["rpc"]}Async(ApiRequest? request = null, CancellationToken ct = default) => StreamAsync({args}, request ?? new(), ct);\n'
        else:
            dotnet += f'    public Task<ApiResponse> {op["rpc"]}Async(ApiRequest? request = null, CancellationToken ct = default) => CallAsync({args}, request ?? new(), ct);\n'
        name = op["rpc"][0].lower() + op["rpc"][1:]
        java += f'    /** {op["method"]} {op["path"]} */\n'
        if stream:
            java += f'    public void {name}(ApiRequest request, Consumer<ApiResponse> onPart) {{ stream({args}, request, onPart); }}\n'
            java += f'    public CompletableFuture<Void> {name}Async(ApiRequest request, Consumer<ApiResponse> onPart) {{ return async(() -> {{ {name}(request, onPart); return null; }}); }}\n'
        else:
            java += f'    public ApiResponse {name}(ApiRequest request) {{ return call({args}, request); }}\n'
            java += f'    public CompletableFuture<ApiResponse> {name}Async(ApiRequest request) {{ return async(() -> {name}(request)); }}\n'
    return {
        "server/proto/mmp/v1/server_api.proto": proto,
        "server/src/munarium-server/src/grpc_api_generated.rs": rust,
        "clients/server-api.json": json.dumps({"server_version": version, "operations": ops}, indent=2) + "\n",
        "clients/python/src/munarium_client/server_api.py": python + python_async.rstrip() + "\n",
        "clients/rust/munarium-client/src/server_api_generated.rs": client_rust + "}\n",
        "clients/dotnet/src/Ioka.Munarium.Client/ServerApiClient.Generated.cs": dotnet + "}\n",
        "clients/java/src/main/java/io/ioka/munarium/client/ServerApiClient.java": java + "}\n",
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for name, body in outputs().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != body:
                stale.append(name)
        else:
            path.write_text(body, encoding="utf-8", newline="\n")
    if stale:
        print("Regenerate Server API: " + ", ".join(stale))
        return 1
    print(f"Server API: {len(operations())} named operations; contract current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
