// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate_server_api.py.
#nullable enable
namespace Ioka.Munarium.Client;
public sealed partial class ServerApiClient {
    /// <summary>GET /healthai</summary>
    public Task<ApiResponse> HealthaiAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("Healthai", "GET", "/healthai", "application/json", request ?? new(), ct);
    /// <summary>GET /healthz</summary>
    public Task<ApiResponse> HealthzAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("Healthz", "GET", "/healthz", "application/json", request ?? new(), ct);
    /// <summary>GET /openapi.json</summary>
    public Task<ApiResponse> OpenapiJsonAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("OpenapiJson", "GET", "/openapi.json", "application/json", request ?? new(), ct);
    /// <summary>GET /readyz</summary>
    public Task<ApiResponse> ReadyzAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("Readyz", "GET", "/readyz", "application/json", request ?? new(), ct);
    /// <summary>POST /v1.2/answers</summary>
    public Task<ApiResponse> ComposeAnswerAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ComposeAnswer", "POST", "/v1.2/answers", "application/json", request ?? new(), ct);
    /// <summary>GET /v1.2/collections/{id}/governance</summary>
    public Task<ApiResponse> GetCollectionGovernanceAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetCollectionGovernance", "GET", "/v1.2/collections/{id}/governance", "application/json", request ?? new(), ct);
    /// <summary>PUT /v1.2/collections/{id}/governance</summary>
    public Task<ApiResponse> ReplaceCollectionGovernanceAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ReplaceCollectionGovernance", "PUT", "/v1.2/collections/{id}/governance", "application/json", request ?? new(), ct);
    /// <summary>GET /v1.2/collections/{id}/publications/{publication_id}</summary>
    public Task<ApiResponse> AuthorizePublicationAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("AuthorizePublication", "GET", "/v1.2/collections/{id}/publications/{publication_id}", "application/json", request ?? new(), ct);
    /// <summary>GET /v1.2/collections/{id}/vocabulary</summary>
    public Task<ApiResponse> GetCollectionVocabularyAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetCollectionVocabulary", "GET", "/v1.2/collections/{id}/vocabulary", "application/json", request ?? new(), ct);
    /// <summary>PATCH /v1.2/collections/{id}/vocabulary</summary>
    public Task<ApiResponse> UpdateCollectionVocabularyAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("UpdateCollectionVocabulary", "PATCH", "/v1.2/collections/{id}/vocabulary", "application/json", request ?? new(), ct);
    /// <summary>PUT /v1.2/collections/{id}/vocabulary</summary>
    public Task<ApiResponse> ReplaceCollectionVocabularyAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ReplaceCollectionVocabulary", "PUT", "/v1.2/collections/{id}/vocabulary", "application/json", request ?? new(), ct);
    /// <summary>POST /v1.2/collections/{id}/vocabulary/refresh</summary>
    public Task<ApiResponse> RefreshCollectionVocabularyAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("RefreshCollectionVocabulary", "POST", "/v1.2/collections/{id}/vocabulary/refresh", "application/json", request ?? new(), ct);
    /// <summary>GET /v1.2/collections/{id}/vocabulary/revision</summary>
    public Task<ApiResponse> GetVocabularyRevisionAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetVocabularyRevision", "GET", "/v1.2/collections/{id}/vocabulary/revision", "application/json", request ?? new(), ct);
    /// <summary>POST /v1.2/query</summary>
    public Task<ApiResponse> QueryCollectionsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("QueryCollections", "POST", "/v1.2/query", "application/json", request ?? new(), ct);
    /// <summary>POST /v1.2/search</summary>
    public Task<ApiResponse> SearchCollectionAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("SearchCollection", "POST", "/v1.2/search", "application/json", request ?? new(), ct);
    /// <summary>GET /v1.2/vocabulary-settings</summary>
    public Task<ApiResponse> GetVocabularySettingsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetVocabularySettings", "GET", "/v1.2/vocabulary-settings", "application/json", request ?? new(), ct);
    /// <summary>PUT /v1.2/vocabulary-settings</summary>
    public Task<ApiResponse> ReplaceVocabularySettingsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ReplaceVocabularySettings", "PUT", "/v1.2/vocabulary-settings", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/access-tokens</summary>
    public Task<ApiResponse> ListTokensAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ListTokens", "GET", "/v1/access-tokens", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/access-tokens</summary>
    public Task<ApiResponse> IssueAccessTokenAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("IssueAccessToken", "POST", "/v1/access-tokens", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/access-tokens/{jti}/revoke</summary>
    public Task<ApiResponse> RevokeTokenAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("RevokeToken", "POST", "/v1/access-tokens/{jti}/revoke", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/authoring/drafts</summary>
    public Task<ApiResponse> ListDraftsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ListDrafts", "GET", "/v1/authoring/drafts", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/authoring/drafts</summary>
    public Task<ApiResponse> CreateDraftAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("CreateDraft", "POST", "/v1/authoring/drafts", "application/json", request ?? new(), ct);
    /// <summary>DELETE /v1/authoring/drafts/{draft_id}</summary>
    public Task<ApiResponse> DeleteDraftAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("DeleteDraft", "DELETE", "/v1/authoring/drafts/{draft_id}", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/authoring/drafts/{draft_id}</summary>
    public Task<ApiResponse> GetDraftAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetDraft", "GET", "/v1/authoring/drafts/{draft_id}", "application/json", request ?? new(), ct);
    /// <summary>PUT /v1/authoring/drafts/{draft_id}/answers</summary>
    public Task<ApiResponse> UpdateAnswersAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("UpdateAnswers", "PUT", "/v1/authoring/drafts/{draft_id}/answers", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/authoring/drafts/{draft_id}/apply</summary>
    public Task<ApiResponse> ApplyDraftAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ApplyDraft", "POST", "/v1/authoring/drafts/{draft_id}/apply", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/authoring/drafts/{draft_id}/assist</summary>
    public Task<ApiResponse> AssistDraftAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("AssistDraft", "POST", "/v1/authoring/drafts/{draft_id}/assist", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/authoring/drafts/{draft_id}/export</summary>
    public Task<ApiResponse> ExportDraftAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ExportDraft", "POST", "/v1/authoring/drafts/{draft_id}/export", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/authoring/drafts/{draft_id}/validate</summary>
    public Task<ApiResponse> ValidateDraftAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ValidateDraft", "POST", "/v1/authoring/drafts/{draft_id}/validate", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/authoring/patterns</summary>
    public Task<ApiResponse> ListPatternsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ListPatterns", "GET", "/v1/authoring/patterns", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/authoring/patterns/{id}</summary>
    public Task<ApiResponse> GetPatternAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetPattern", "GET", "/v1/authoring/patterns/{id}", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/budgets/{id}/adjustments</summary>
    public Task<ApiResponse> BudgetAdjustmentsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("BudgetAdjustments", "GET", "/v1/budgets/{id}/adjustments", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/budgets/{id}/adjustments</summary>
    public Task<ApiResponse> ReconcileBudgetAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ReconcileBudget", "POST", "/v1/budgets/{id}/adjustments", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/budgets/{id}/evidence</summary>
    public Task<ApiResponse> BudgetEvidenceAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("BudgetEvidence", "GET", "/v1/budgets/{id}/evidence", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/chronology-rules</summary>
    public Task<ApiResponse> ApplyRulesAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ApplyRules", "POST", "/v1/chronology-rules", "text/yaml", request ?? new(), ct);
    /// <summary>GET /v1/chronology-rules/{name}</summary>
    public Task<ApiResponse> GetRulesAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetRules", "GET", "/v1/chronology-rules/{name}", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/claims/{claim_id}</summary>
    public Task<ApiResponse> GetClaimAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetClaim", "GET", "/v1/claims/{claim_id}", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/collections</summary>
    public Task<ApiResponse> ListCollectionsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ListCollections", "GET", "/v1/collections", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/collections</summary>
    public Task<ApiResponse> CreateCollectionAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("CreateCollection", "POST", "/v1/collections", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/collections/{collection_id}/activate-index</summary>
    public Task<ApiResponse> ActivateCollectionIndexAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ActivateCollectionIndex", "POST", "/v1/collections/{collection_id}/activate-index", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/collections/{id}</summary>
    public Task<ApiResponse> GetCollectionAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetCollection", "GET", "/v1/collections/{id}", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/command-recovery</summary>
    public Task<ApiResponse> CommandRecoveryPolicyAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("CommandRecoveryPolicy", "GET", "/v1/command-recovery", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/command-recovery</summary>
    public Task<ApiResponse> EnableCommandRecoveryAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("EnableCommandRecovery", "POST", "/v1/command-recovery", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/command-recovery/receipt</summary>
    public Task<ApiResponse> CommandRecoveryReceiptAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("CommandRecoveryReceipt", "GET", "/v1/command-recovery/receipt", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/evidence</summary>
    public Task<ApiResponse> SealAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("Seal", "POST", "/v1/evidence", "application/json", request ?? new(), ct);
    /// <summary>DELETE /v1/evidence/{evidence_id}</summary>
    public Task<ApiResponse> PurgeAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("Purge", "DELETE", "/v1/evidence/{evidence_id}", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/evidence/{evidence_id}</summary>
    public Task<ApiResponse> GetManifestAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetManifest", "GET", "/v1/evidence/{evidence_id}", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/evidence/{evidence_id}/accesses</summary>
    public Task<ApiResponse> GetAccessesAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetAccesses", "GET", "/v1/evidence/{evidence_id}/accesses", "application/json", request ?? new(), ct);
    /// <summary>PUT /v1/evidence/{evidence_id}/bytes</summary>
    public Task<ApiResponse> PutBytesAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("PutBytes", "PUT", "/v1/evidence/{evidence_id}/bytes", "application/octet-stream", request ?? new(), ct);
    /// <summary>POST /v1/evidence/{evidence_id}/commit</summary>
    public Task<ApiResponse> CommitAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("Commit", "POST", "/v1/evidence/{evidence_id}/commit", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/evidence/{evidence_id}/legal-hold</summary>
    public Task<ApiResponse> LegalHoldAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("LegalHold", "POST", "/v1/evidence/{evidence_id}/legal-hold", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/evidence/{evidence_id}/rows</summary>
    public Task<ApiResponse> GetRowsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetRows", "GET", "/v1/evidence/{evidence_id}/rows", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/index-artifacts/backfill</summary>
    public Task<ApiResponse> BackfillAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("Backfill", "POST", "/v1/index-artifacts/backfill", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/index-artifacts/{index_version_id}</summary>
    public Task<ApiResponse> ArtifactStatusAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ArtifactStatus", "GET", "/v1/index-artifacts/{index_version_id}", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/index-artifacts/{index_version_id}/bind</summary>
    public Task<ApiResponse> BindArtifactAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("BindArtifact", "POST", "/v1/index-artifacts/{index_version_id}/bind", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/index-artifacts/{index_version_id}/promote</summary>
    public Task<ApiResponse> PromoteArtifactAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("PromoteArtifact", "POST", "/v1/index-artifacts/{index_version_id}/promote", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/index-artifacts/{index_version_id}/rebuild</summary>
    public Task<ApiResponse> RebuildArtifactAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("RebuildArtifact", "POST", "/v1/index-artifacts/{index_version_id}/rebuild", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/index-artifacts/{index_version_id}/verify</summary>
    public Task<ApiResponse> VerifyArtifactsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("VerifyArtifacts", "POST", "/v1/index-artifacts/{index_version_id}/verify", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/index-build-jobs</summary>
    public Task<ApiResponse> ListJobsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ListJobs", "GET", "/v1/index-build-jobs", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/index-build-jobs</summary>
    public Task<ApiResponse> EnqueueJobAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("EnqueueJob", "POST", "/v1/index-build-jobs", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/index-build-jobs/{job_id}</summary>
    public Task<ApiResponse> GetJobAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetJob", "GET", "/v1/index-build-jobs/{job_id}", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/index-build-jobs/{job_id}/cancel</summary>
    public Task<ApiResponse> CancelJobAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("CancelJob", "POST", "/v1/index-build-jobs/{job_id}/cancel", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/indexes/{shape_ref}</summary>
    public Task<ApiResponse> GetIndexAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetIndex", "GET", "/v1/indexes/{shape_ref}", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/indexes/{shape_ref}/build</summary>
    public Task<ApiResponse> BuildIndexAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("BuildIndex", "POST", "/v1/indexes/{shape_ref}/build", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/ingest</summary>
    public Task<ApiResponse> IngestFileAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("IngestFile", "POST", "/v1/ingest", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/ingest/batch</summary>
    public Task<ApiResponse> IngestBatchAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("IngestBatch", "POST", "/v1/ingest/batch", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/ingest/bulk</summary>
    public Task<ApiResponse> BulkOpenAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("BulkOpen", "POST", "/v1/ingest/bulk", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/ingest/bulk/{bulk_id}</summary>
    public Task<ApiResponse> BulkStatusAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("BulkStatus", "GET", "/v1/ingest/bulk/{bulk_id}", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/ingest/bulk/{bulk_id}/chunk</summary>
    public Task<ApiResponse> BulkChunkAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("BulkChunk", "POST", "/v1/ingest/bulk/{bulk_id}/chunk", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/ingest/bulk/{bulk_id}/complete</summary>
    public Task<ApiResponse> BulkCompleteAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("BulkComplete", "POST", "/v1/ingest/bulk/{bulk_id}/complete", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/max-tokens</summary>
    public Task<ApiResponse> GetMaxTokensAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetMaxTokens", "GET", "/v1/max-tokens", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/max-tokens</summary>
    public Task<ApiResponse> ReplaceMaxTokensAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ReplaceMaxTokens", "POST", "/v1/max-tokens", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/monetary/observations</summary>
    public Task<ApiResponse> AddMonetaryObservationAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("AddMonetaryObservation", "POST", "/v1/monetary/observations", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/monetary/prices</summary>
    public Task<ApiResponse> MonetaryPricesAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("MonetaryPrices", "GET", "/v1/monetary/prices", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/monetary/prices</summary>
    public Task<ApiResponse> AddMonetaryPriceAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("AddMonetaryPrice", "POST", "/v1/monetary/prices", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/providers</summary>
    public Task<ApiResponse> ListProvidersAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ListProviders", "GET", "/v1/providers", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/providers</summary>
    public Task<ApiResponse> ApplyProviderAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ApplyProvider", "POST", "/v1/providers", "text/yaml", request ?? new(), ct);
    /// <summary>POST /v1/providers/{name}/complete</summary>
    public Task<ApiResponse> ProviderCompleteAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ProviderComplete", "POST", "/v1/providers/{name}/complete", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/providers/{name}/diagnostics</summary>
    public Task<ApiResponse> ProviderDiagnosticsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ProviderDiagnostics", "GET", "/v1/providers/{name}/diagnostics", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/providers/{name}/embed</summary>
    public Task<ApiResponse> ProviderEmbedAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ProviderEmbed", "POST", "/v1/providers/{name}/embed", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/providers/{name}/health</summary>
    public Task<ApiResponse> ProviderHealthAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ProviderHealth", "GET", "/v1/providers/{name}/health", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/reports/audit</summary>
    public Task<ApiResponse> AuditAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("Audit", "GET", "/v1/reports/audit", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/reports/budget-usage</summary>
    public Task<ApiResponse> BudgetUsageReportAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("BudgetUsageReport", "GET", "/v1/reports/budget-usage", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/reports/budgets</summary>
    public Task<ApiResponse> BudgetsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("Budgets", "GET", "/v1/reports/budgets", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/reports/cost</summary>
    public Task<ApiResponse> CostAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("Cost", "GET", "/v1/reports/cost", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/reports/endpoints</summary>
    public Task<ApiResponse> EndpointsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("Endpoints", "GET", "/v1/reports/endpoints", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/reports/evidence</summary>
    public Task<ApiResponse> EvidenceReportAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("EvidenceReport", "GET", "/v1/reports/evidence", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/reports/matrix</summary>
    public Task<ApiResponse> MatrixReportAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("MatrixReport", "GET", "/v1/reports/matrix", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/reports/money</summary>
    public Task<ApiResponse> MonetaryReportAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("MonetaryReport", "GET", "/v1/reports/money", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/reports/runbooks</summary>
    public Task<ApiResponse> RunbookReportAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("RunbookReport", "GET", "/v1/reports/runbooks", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/reports/sessions</summary>
    public Task<ApiResponse> SessionsReportAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("SessionsReport", "GET", "/v1/reports/sessions", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/reports/timeseries</summary>
    public Task<ApiResponse> TimeseriesAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("Timeseries", "GET", "/v1/reports/timeseries", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/reports/usage</summary>
    public Task<ApiResponse> UsageAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("Usage", "GET", "/v1/reports/usage", "application/json", request ?? new(), ct);
    /// <summary>PUT /v1/retrieval-rollout</summary>
    public Task<ApiResponse> RolloutSetAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("RolloutSet", "PUT", "/v1/retrieval-rollout", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/retrieval-rollout/{scope_kind}/{scope_id}</summary>
    public Task<ApiResponse> RolloutGetAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("RolloutGet", "GET", "/v1/retrieval-rollout/{scope_kind}/{scope_id}", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/runbooks</summary>
    public Task<ApiResponse> ListRunbooksAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ListRunbooks", "GET", "/v1/runbooks", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/runbooks</summary>
    public Task<ApiResponse> ApplyRunbookAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ApplyRunbook", "POST", "/v1/runbooks", "text/yaml", request ?? new(), ct);
    /// <summary>POST /v1/runbooks/validate</summary>
    public Task<ApiResponse> ValidateRunbookAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ValidateRunbook", "POST", "/v1/runbooks/validate", "text/yaml", request ?? new(), ct);
    /// <summary>GET /v1/runbooks/{name}</summary>
    public Task<ApiResponse> GetRunbookInfoAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetRunbookInfo", "GET", "/v1/runbooks/{name}", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/runbooks/{name}/remove-confirm</summary>
    public Task<ApiResponse> RemoveConfirmAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("RemoveConfirm", "POST", "/v1/runbooks/{name}/remove-confirm", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/runbooks/{name}/remove-request</summary>
    public Task<ApiResponse> RemoveRequestAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("RemoveRequest", "POST", "/v1/runbooks/{name}/remove-request", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/runbooks/{name}/runs</summary>
    public Task<ApiResponse> RunRunbookAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("RunRunbook", "POST", "/v1/runbooks/{name}/runs", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/runbooks/{name}/sessions</summary>
    public Task<ApiResponse> CreateSessionAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("CreateSession", "POST", "/v1/runbooks/{name}/sessions", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/runs/{run_id}</summary>
    public Task<ApiResponse> GetRunAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetRun", "GET", "/v1/runs/{run_id}", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/runs/{run_id}/steps/{ordinal}/approve</summary>
    public Task<ApiResponse> ApproveStepAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ApproveStep", "POST", "/v1/runs/{run_id}/steps/{ordinal}/approve", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/search</summary>
    public Task<ApiResponse> HybridSearchAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("HybridSearch", "POST", "/v1/search", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/sessions/{id}</summary>
    public Task<ApiResponse> GetSessionAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetSession", "GET", "/v1/sessions/{id}", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/sessions/{id}/close</summary>
    public Task<ApiResponse> CloseSessionAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("CloseSession", "POST", "/v1/sessions/{id}/close", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/sessions/{id}/turns</summary>
    public Task<ApiResponse> TurnAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("Turn", "POST", "/v1/sessions/{id}/turns", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/sessions/{id}/turns/stream</summary>
    public IAsyncEnumerable<ApiResponse> TurnStreamAsync(ApiRequest? request = null, CancellationToken ct = default) => StreamAsync("TurnStream", "POST", "/v1/sessions/{id}/turns/stream", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/shapes</summary>
    public Task<ApiResponse> ApplyShapeAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ApplyShape", "POST", "/v1/shapes", "text/yaml", request ?? new(), ct);
    /// <summary>PUT /v1/sources</summary>
    public Task<ApiResponse> PutSourceAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("PutSource", "PUT", "/v1/sources", "application/octet-stream", request ?? new(), ct);
    /// <summary>GET /v1/sources/{source_id}</summary>
    public Task<ApiResponse> GetSourceAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetSource", "GET", "/v1/sources/{source_id}", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/versions</summary>
    public Task<ApiResponse> CreateVersionAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("CreateVersion", "POST", "/v1/versions", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/versions/{version_id}/anchors</summary>
    public Task<ApiResponse> GetAnchorsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetAnchors", "GET", "/v1/versions/{version_id}/anchors", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/versions/{version_id}/anchors</summary>
    public Task<ApiResponse> LockAnchorAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("LockAnchor", "POST", "/v1/versions/{version_id}/anchors", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/versions/{version_id}/claims</summary>
    public Task<ApiResponse> ProposeClaimAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("ProposeClaim", "POST", "/v1/versions/{version_id}/claims", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/versions/{version_id}/context</summary>
    public Task<ApiResponse> GetContextAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetContext", "GET", "/v1/versions/{version_id}/context", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/versions/{version_id}/counters</summary>
    public Task<ApiResponse> GetCountersAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetCounters", "GET", "/v1/versions/{version_id}/counters", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/versions/{version_id}/counters</summary>
    public Task<ApiResponse> RecordCountsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("RecordCounts", "POST", "/v1/versions/{version_id}/counters", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/versions/{version_id}/digests</summary>
    public Task<ApiResponse> GetDigestsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetDigests", "GET", "/v1/versions/{version_id}/digests", "application/json", request ?? new(), ct);
    /// <summary>PUT /v1/versions/{version_id}/digests</summary>
    public Task<ApiResponse> UpsertDigestAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("UpsertDigest", "PUT", "/v1/versions/{version_id}/digests", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/versions/{version_id}/events</summary>
    public Task<ApiResponse> AppendEventsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("AppendEvents", "POST", "/v1/versions/{version_id}/events", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/versions/{version_id}/facts</summary>
    public Task<ApiResponse> GetFactsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetFacts", "GET", "/v1/versions/{version_id}/facts", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/versions/{version_id}/findings</summary>
    public Task<ApiResponse> GetFindingsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetFindings", "GET", "/v1/versions/{version_id}/findings", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/versions/{version_id}/findings</summary>
    public Task<ApiResponse> RecordFindingsAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("RecordFindings", "POST", "/v1/versions/{version_id}/findings", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/versions/{version_id}/head</summary>
    public Task<ApiResponse> GetHeadAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetHead", "GET", "/v1/versions/{version_id}/head", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/versions/{version_id}/ingests</summary>
    public Task<ApiResponse> RecordIngestAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("RecordIngest", "POST", "/v1/versions/{version_id}/ingests", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/versions/{version_id}/lineage</summary>
    public Task<ApiResponse> GetLineageAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetLineage", "GET", "/v1/versions/{version_id}/lineage", "application/json", request ?? new(), ct);
    /// <summary>GET /v1/versions/{version_id}/promises</summary>
    public Task<ApiResponse> GetPromisesAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("GetPromises", "GET", "/v1/versions/{version_id}/promises", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/versions/{version_id}/promises</summary>
    public Task<ApiResponse> OpenPromiseAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("OpenPromise", "POST", "/v1/versions/{version_id}/promises", "application/json", request ?? new(), ct);
    /// <summary>POST /v1/versions/{version_id}/promises/{key}/fulfill</summary>
    public Task<ApiResponse> FulfillPromiseAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("FulfillPromise", "POST", "/v1/versions/{version_id}/promises/{key}/fulfill", "application/json", request ?? new(), ct);
    /// <summary>GET /version</summary>
    public Task<ApiResponse> VersionInfoAsync(ApiRequest? request = null, CancellationToken ct = default) => CallAsync("VersionInfo", "GET", "/version", "application/json", request ?? new(), ct);
}
